import { marketingLinks } from "@/lib/marketing-links";

export type PricingPlanTone = "neutral" | "featured" | "premium";

export type PricingPlan = {
  id: string;
  eyebrow: string;
  title: string;
  description: string;
  price: string;
  priceSuffix: string;
  secondaryPrice: string;
  note: string;
  ctaLabel: string;
  ctaHref: string;
  tone: PricingPlanTone;
  features: string[];
  badge?: string;
};

type PricingLocaleContent = {
  homeFreeTierFeatures: string[];
  homePaidAccessFeatures: string[];
  freeTierPricingFeatures: string[];
  paidAccessComparisonFeatures: string[];
  featureLabel: string;
  pricingPlans: Array<Omit<PricingPlan, "ctaHref"> & { ctaKey: "free" | "pro" | "lifetime" }>;
};

const pricingContentByLocale: Record<"en" | "pt" | "es" | "fr" | "ru" | "zh", PricingLocaleContent> = {
  en: {
    homeFreeTierFeatures: [
      "Manual replication controls",
      "Automated replication controls",
      "Compliance enforcement",
      "1 master group included",
      "Up to 2 follower accounts",
      "Risk control indicators",
      "Preloaded prop firm rules",
      "Chart Trader Replicate and Flatten All controls",
      "Core assistant layer for disciplined prop trading",
    ],
    freeTierPricingFeatures: [
      "Manual + auto replication",
      "Compliance + firm rules",
      "1 master + 2 followers",
      "Risk control indicators",
      "Replicate + Flatten All",
      "Core assistant layer",
    ],
    paidAccessComparisonFeatures: [
      "10 groups + 100 followers each",
      "Glitch Score across 1m, 5m, 15m, and 60m",
      "Journal, Metrics + Insights",
      "Technical, macro + sentiment context",
      "Nasdaq + Mag7 enriched data",
      "Bring your own indicators + bots",
    ],
    homePaidAccessFeatures: [
      "Up to 10 groups / masters",
      "Up to 100 followers per group",
      "Glitch Score across 1m, 5m, 15m, and 60m timeframes",
      "Journal, Metrics, and Insights performance engine",
      "Regime, technical, order-flow, fundamental, and macro context",
      "Nasdaq + Mag7 enriched data + news sentiment overlays",
      "Bring your own indicators, strategies, and bots",
    ],
    featureLabel: "What you get",
    pricingPlans: [
      {
        id: "free-tier",
        eyebrow: "Free",
        title: "Start with guardrails",
        description: "Protect accounts, validate the workflow, and get the core assistant layer running before you pay.",
        price: "$0",
        priceSuffix: "to start",
        secondaryPrice: "Fast onboarding",
        note: "Install quickly, learn the workflow, and upgrade only when the operation is ready for more scale.",
        ctaLabel: "Start Free",
        ctaKey: "free",
        tone: "neutral",
        features: [
          "Manual + auto replication",
          "Compliance + firm rules",
          "1 master + 2 followers",
          "Risk control indicators",
          "Replicate + Flatten All",
          "Core assistant layer",
        ],
      },
      {
        id: "go-pro",
        eyebrow: "Monthly / Annual",
        title: "Flexible premium access",
        description: "Unlock the full premium stack with billing that fits active traders and growing account operations.",
        price: "$95",
        priceSuffix: "/ month",
        secondaryPrice: "or $995 / year",
        note: "Choose monthly or yearly in checkout. Same premium toolset either way.",
        ctaLabel: "Go Pro",
        ctaKey: "pro",
        tone: "featured",
        badge: "Most popular",
        features: [
          "Up to 10 groups / masters",
          "Up to 100 followers per group",
          "Glitch Score across 1m, 5m, 15m, and 60m timeframes",
          "Journal, Metrics, and Insights engine",
          "Nasdaq, Mag7, macro, and news sentiment context",
        ],
      },
      {
        id: "lifetime-access",
        eyebrow: "Lifetime access",
        title: "Own the operating layer",
        description: "Get the same premium Glitch stack without recurring billing when you already know this is core infrastructure.",
        price: "$2,450",
        priceSuffix: "one time",
        secondaryPrice: "No recurring bill",
        note: "One payment. Full premium access. Best fit for traders building a long-term operating stack.",
        ctaLabel: "Get Lifetime Access",
        ctaKey: "lifetime",
        tone: "premium",
        features: [
          "Everything in Monthly / Annual",
          "Bring your own indicators, strategies, and bots",
          "Same premium compliance, replication, and analytics stack",
          "One payment instead of recurring billing",
          "Best economics for long-term operators",
        ],
      },
    ],
  },
  pt: {
    homeFreeTierFeatures: [
      "Controles de replicação manual",
      "Controles de replicação automática",
      "Aplicação de conformidade",
      "1 grupo master incluído",
      "Até 2 contas seguidoras",
      "Indicadores de controle de risco",
      "Regras de prop firms pré-carregadas",
      "Controles Replicate e Flatten All no Chart Trader",
      "Camada central de assistência para prop trading disciplinado",
    ],
    freeTierPricingFeatures: [
      "Replicação manual + automática",
      "Conformidade + regras da firma",
      "1 master + 2 seguidores",
      "Indicadores de risco",
      "Replicate + Flatten All",
      "Camada central do assistente",
    ],
    paidAccessComparisonFeatures: [
      "10 grupos + 100 seguidores cada",
      "Glitch Score em 1m, 5m, 15m e 60m",
      "Journal, Metrics + Insights",
      "Contexto técnico, macro + sentimento",
      "Dados enriquecidos Nasdaq + Mag7",
      "Use seus indicadores + bots",
    ],
    homePaidAccessFeatures: [
      "Até 10 grupos / masters",
      "Até 100 seguidores por grupo",
      "Glitch Score em timeframes de 1m, 5m, 15m e 60m",
      "Engine de performance com Journal, Metrics e Insights",
      "Contexto de regime, técnico, fluxo, fundamental e macro",
      "Dados enriquecidos de Nasdaq + Mag7 + sentimento de notícias",
      "Use seus próprios indicadores, estratégias e bots",
    ],
    featureLabel: "O que você recebe",
    pricingPlans: [
      {
        id: "free-tier",
        eyebrow: "Grátis",
        title: "Comece com proteção",
        description: "Proteja contas, valide o fluxo e coloque a camada central do assistente para rodar antes de pagar.",
        price: "$0",
        priceSuffix: "para começar",
        secondaryPrice: "Onboarding rápido",
        note: "Instale rápido, aprenda o fluxo e faça upgrade só quando a operação pedir mais escala.",
        ctaLabel: "Começar grátis",
        ctaKey: "free",
        tone: "neutral",
        features: [
          "Replicação manual + automática",
          "Conformidade + regras da firma",
          "1 master + 2 seguidores",
          "Indicadores de risco",
          "Replicate + Flatten All",
          "Camada central do assistente",
        ],
      },
      {
        id: "go-pro",
        eyebrow: "Mensal / Anual",
        title: "Acesso premium flexível",
        description: "Libere toda a stack premium com cobrança que acompanha traders ativos e operações em crescimento.",
        price: "$95",
        priceSuffix: "/ mês",
        secondaryPrice: "ou $995 / ano",
        note: "Escolha mensal ou anual no checkout. A ferramenta premium é a mesma.",
        ctaLabel: "Go Pro",
        ctaKey: "pro",
        tone: "featured",
        badge: "Mais popular",
        features: [
          "Até 10 grupos / masters",
          "Até 100 seguidores por grupo",
          "Glitch Score em timeframes de 1m, 5m, 15m e 60m",
          "Engine de Journal, Metrics e Insights",
          "Contexto de Nasdaq, Mag7, macro e sentimento de notícias",
        ],
      },
      {
        id: "lifetime-access",
        eyebrow: "Acesso vitalício",
        title: "Tenha a camada operacional",
        description: "Receba a mesma stack premium do Glitch sem cobrança recorrente quando isso já faz parte da sua infraestrutura.",
        price: "$2,450",
        priceSuffix: "uma vez",
        secondaryPrice: "Sem cobrança recorrente",
        note: "Um pagamento. Acesso premium completo. Melhor escolha para traders construindo uma stack de longo prazo.",
        ctaLabel: "Obter acesso vitalício",
        ctaKey: "lifetime",
        tone: "premium",
        features: [
          "Tudo do Mensal / Anual",
          "Use seus próprios indicadores, estratégias e bots",
          "A mesma stack premium de conformidade, replicação e analytics",
          "Um pagamento em vez de cobrança recorrente",
          "Melhor economia para operadores de longo prazo",
        ],
      },
    ],
  },
  es: {
    homeFreeTierFeatures: [
      "Controles de replicación manual",
      "Controles de replicación automática",
      "Aplicación de cumplimiento",
      "1 grupo master incluido",
      "Hasta 2 cuentas seguidoras",
      "Indicadores de control de riesgo",
      "Reglas de prop firms precargadas",
      "Controles Replicate y Flatten All en Chart Trader",
      "Capa central de asistencia para prop trading disciplinado",
    ],
    freeTierPricingFeatures: [
      "Replicación manual + automática",
      "Cumplimiento + reglas de la firma",
      "1 master + 2 seguidores",
      "Indicadores de riesgo",
      "Replicate + Flatten All",
      "Capa central del asistente",
    ],
    paidAccessComparisonFeatures: [
      "10 grupos + 100 seguidores cada uno",
      "Glitch Score en 1m, 5m, 15m y 60m",
      "Journal, Metrics + Insights",
      "Contexto técnico, macro + sentimiento",
      "Datos enriquecidos de Nasdaq + Mag7",
      "Usa tus indicadores + bots",
    ],
    homePaidAccessFeatures: [
      "Hasta 10 grupos / masters",
      "Hasta 100 seguidores por grupo",
      "Glitch Score en marcos de 1m, 5m, 15m y 60m",
      "Motor de rendimiento con Journal, Metrics e Insights",
      "Contexto de régimen, técnico, order-flow, fundamental y macro",
      "Datos enriquecidos de Nasdaq + Mag7 + sentimiento de noticias",
      "Usa tus propios indicadores, estrategias y bots",
    ],
    featureLabel: "Lo que obtienes",
    pricingPlans: [
      {
        id: "free-tier",
        eyebrow: "Gratis",
        title: "Empieza con guardrails",
        description: "Protege cuentas, valida el flujo y pon en marcha la capa central del asistente antes de pagar.",
        price: "$0",
        priceSuffix: "para empezar",
        secondaryPrice: "Onboarding rápido",
        note: "Instala rápido, aprende el flujo y actualiza solo cuando la operación pida más escala.",
        ctaLabel: "Empezar gratis",
        ctaKey: "free",
        tone: "neutral",
        features: [
          "Replicación manual + automática",
          "Cumplimiento + reglas de la firma",
          "1 master + 2 seguidores",
          "Indicadores de riesgo",
          "Replicate + Flatten All",
          "Capa central del asistente",
        ],
      },
      {
        id: "go-pro",
        eyebrow: "Mensual / Anual",
        title: "Acceso premium flexible",
        description: "Desbloquea toda la stack premium con una facturación que encaja con traders activos y operaciones en crecimiento.",
        price: "$95",
        priceSuffix: "/ mes",
        secondaryPrice: "o $995 / año",
        note: "Elige mensual o anual en checkout. La herramienta premium es la misma.",
        ctaLabel: "Go Pro",
        ctaKey: "pro",
        tone: "featured",
        badge: "Más popular",
        features: [
          "Hasta 10 grupos / masters",
          "Hasta 100 seguidores por grupo",
          "Glitch Score en marcos de 1m, 5m, 15m y 60m",
          "Motor de Journal, Metrics e Insights",
          "Contexto de Nasdaq, Mag7, macro y sentimiento de noticias",
        ],
      },
      {
        id: "lifetime-access",
        eyebrow: "Acceso vitalicio",
        title: "Haz tuya la capa operativa",
        description: "Obtén la misma stack premium de Glitch sin facturación recurrente cuando ya sabes que es infraestructura central.",
        price: "$2,450",
        priceSuffix: "una vez",
        secondaryPrice: "Sin cargo recurrente",
        note: "Un pago. Acceso premium completo. Mejor encaje para traders que construyen una stack operativa de largo plazo.",
        ctaLabel: "Obtener acceso vitalicio",
        ctaKey: "lifetime",
        tone: "premium",
        features: [
          "Todo lo de Mensual / Anual",
          "Usa tus propios indicadores, estrategias y bots",
          "La misma stack premium de cumplimiento, replicación y analítica",
          "Un pago en lugar de cobro recurrente",
          "Mejor economía para operadores de largo plazo",
        ],
      },
    ],
  },
  fr: {
    homeFreeTierFeatures: [
      "Contrôles de réplication manuelle",
      "Contrôles de réplication automatique",
      "Application de conformité",
      "1 groupe master inclus",
      "Jusqu’à 2 comptes followers",
      "Indicateurs de contrôle du risque",
      "Règles de prop firms préchargées",
      "Contrôles Replicate et Flatten All dans Chart Trader",
      "Couche centrale d’assistance pour un prop trading discipliné",
    ],
    freeTierPricingFeatures: [
      "Réplication manuelle + automatique",
      "Conformité + règles de firme",
      "1 master + 2 followers",
      "Indicateurs de risque",
      "Replicate + Flatten All",
      "Couche centrale de l’assistant",
    ],
    paidAccessComparisonFeatures: [
      "10 groupes + 100 followers chacun",
      "Glitch Score sur 1m, 5m, 15m et 60m",
      "Journal, Metrics + Insights",
      "Contexte technique, macro + sentiment",
      "Données enrichies Nasdaq + Mag7",
      "Utilisez vos indicateurs + bots",
    ],
    homePaidAccessFeatures: [
      "Jusqu’à 10 groupes / masters",
      "Jusqu’à 100 followers par groupe",
      "Glitch Score sur 1m, 5m, 15m et 60m",
      "Moteur de performance Journal, Metrics et Insights",
      "Contexte de régime, technique, order-flow, fondamental et macro",
      "Données enrichies Nasdaq + Mag7 + sentiment news",
      "Utilisez vos propres indicateurs, stratégies et bots",
    ],
    featureLabel: "Ce que vous obtenez",
    pricingPlans: [
      {
        id: "free-tier",
        eyebrow: "Gratuit",
        title: "Commencez avec des garde-fous",
        description: "Protégez les comptes, validez le workflow et mettez en route la couche centrale de l’assistant avant de payer.",
        price: "$0",
        priceSuffix: "pour commencer",
        secondaryPrice: "Onboarding rapide",
        note: "Installez rapidement, apprenez le workflow et upgradez seulement quand l’opération réclame plus d’échelle.",
        ctaLabel: "Commencer gratuitement",
        ctaKey: "free",
        tone: "neutral",
        features: [
          "Réplication manuelle + automatique",
          "Conformité + règles de firme",
          "1 master + 2 followers",
          "Indicateurs de risque",
          "Replicate + Flatten All",
          "Couche centrale de l’assistant",
        ],
      },
      {
        id: "go-pro",
        eyebrow: "Mensuel / Annuel",
        title: "Accès premium flexible",
        description: "Débloquez toute la stack premium avec une facturation qui convient aux traders actifs et aux opérations en croissance.",
        price: "$95",
        priceSuffix: "/ mois",
        secondaryPrice: "ou $995 / an",
        note: "Choisissez mensuel ou annuel au checkout. L’outil premium reste le même.",
        ctaLabel: "Go Pro",
        ctaKey: "pro",
        tone: "featured",
        badge: "Le plus populaire",
        features: [
          "Jusqu’à 10 groupes / masters",
          "Jusqu’à 100 followers par groupe",
          "Glitch Score sur 1m, 5m, 15m et 60m",
          "Moteur Journal, Metrics et Insights",
          "Contexte Nasdaq, Mag7, macro et sentiment news",
        ],
      },
      {
        id: "lifetime-access",
        eyebrow: "Accès à vie",
        title: "Possédez la couche opérationnelle",
        description: "Recevez la même stack premium Glitch sans facturation récurrente lorsque vous savez déjà qu’elle fait partie de votre infrastructure.",
        price: "$2,450",
        priceSuffix: "une fois",
        secondaryPrice: "Sans facturation récurrente",
        note: "Un paiement. Accès premium complet. Le meilleur choix pour les traders qui construisent une stack durable.",
        ctaLabel: "Obtenir l’accès à vie",
        ctaKey: "lifetime",
        tone: "premium",
        features: [
          "Tout le contenu du Mensuel / Annuel",
          "Utilisez vos indicateurs, stratégies et bots",
          "La même stack premium de conformité, réplication et analytics",
          "Un paiement au lieu d’une facturation récurrente",
          "Meilleure économie pour les opérateurs long terme",
        ],
      },
    ],
  },
  ru: {
    homeFreeTierFeatures: [
      "Контроль ручной репликации",
      "Контроль автоматической репликации",
      "Слой соблюдения правил",
      "1 master-группа включена",
      "До 2 follower-счетов",
      "Индикаторы контроля риска",
      "Предзагруженные правила prop firms",
      "Контроли Replicate и Flatten All в Chart Trader",
      "Центральный слой ассистента для дисциплинированного prop trading",
    ],
    freeTierPricingFeatures: [
      "Ручная + автоматическая репликация",
      "Соблюдение правил + лимиты фирмы",
      "1 master + 2 followers",
      "Индикаторы риска",
      "Replicate + Flatten All",
      "Центральный слой ассистента",
    ],
    paidAccessComparisonFeatures: [
      "10 групп + 100 followers в каждой",
      "Glitch Score на 1m, 5m, 15m и 60m",
      "Journal, Metrics + Insights",
      "Технический, макро + sentiment-контекст",
      "Обогащенные данные Nasdaq + Mag7",
      "Используйте свои индикаторы + ботов",
    ],
    homePaidAccessFeatures: [
      "До 10 groups / masters",
      "До 100 followers на группу",
      "Glitch Score на 1m, 5m, 15m и 60m",
      "Performance engine с Journal, Metrics и Insights",
      "Контекст режима, техники, order-flow, фундаментала и macro",
      "Обогащенные данные Nasdaq + Mag7 + news sentiment",
      "Используйте свои индикаторы, стратегии и ботов",
    ],
    featureLabel: "Что вы получаете",
    pricingPlans: [
      {
        id: "free-tier",
        eyebrow: "Бесплатно",
        title: "Начните с guardrails",
        description: "Защитите счета, проверьте workflow и запустите центральный слой ассистента до оплаты.",
        price: "$0",
        priceSuffix: "на старте",
        secondaryPrice: "Быстрый onboarding",
        note: "Быстро установите, разберитесь с workflow и обновляйтесь только тогда, когда операции потребуется больше масштаба.",
        ctaLabel: "Начать бесплатно",
        ctaKey: "free",
        tone: "neutral",
        features: [
          "Ручная + автоматическая репликация",
          "Соблюдение правил + лимиты фирмы",
          "1 master + 2 followers",
          "Индикаторы риска",
          "Replicate + Flatten All",
          "Центральный слой ассистента",
        ],
      },
      {
        id: "go-pro",
        eyebrow: "Месяц / Год",
        title: "Гибкий premium-доступ",
        description: "Откройте всю premium stack с моделью оплаты, подходящей активным трейдерам и растущим операциям.",
        price: "$95",
        priceSuffix: "/ месяц",
        secondaryPrice: "или $995 / год",
        note: "Выберите месячную или годовую оплату при checkout. Premium-инструментарий одинаков.",
        ctaLabel: "Go Pro",
        ctaKey: "pro",
        tone: "featured",
        badge: "Самый популярный",
        features: [
          "До 10 groups / masters",
          "До 100 followers на группу",
          "Glitch Score на 1m, 5m, 15m и 60m",
          "Journal, Metrics и Insights engine",
          "Контекст Nasdaq, Mag7, macro и news sentiment",
        ],
      },
      {
        id: "lifetime-access",
        eyebrow: "Lifetime доступ",
        title: "Сделайте операционный слой своим",
        description: "Получите ту же premium stack Glitch без регулярной оплаты, если уже знаете, что это часть вашей инфраструктуры.",
        price: "$2,450",
        priceSuffix: "один раз",
        secondaryPrice: "Без рекуррентных списаний",
        note: "Один платеж. Полный premium-доступ. Лучший вариант для долгосрочной операционной stack.",
        ctaLabel: "Получить lifetime доступ",
        ctaKey: "lifetime",
        tone: "premium",
        features: [
          "Все из Monthly / Annual",
          "Используйте свои индикаторы, стратегии и ботов",
          "Та же premium stack по соответствию, репликации и аналитике",
          "Один платеж вместо рекуррентной оплаты",
          "Лучшая экономика для долгосрочных операторов",
        ],
      },
    ],
  },
  zh: {
    homeFreeTierFeatures: [
      "手动复制控制",
      "自动复制控制",
      "合规执行",
      "包含 1 个 master group",
      "最多 2 个 follower 账户",
      "风险控制指标",
      "预置 prop firm 规则",
      "Chart Trader 中的 Replicate 与 Flatten All 控制",
      "面向纪律化 prop trading 的核心助手层",
    ],
    freeTierPricingFeatures: [
      "手动 + 自动复制",
      "合规 + firm 规则",
      "1 个 master + 2 个 follower",
      "风险控制指标",
      "Replicate + Flatten All",
      "核心助手层",
    ],
    paidAccessComparisonFeatures: [
      "10 个 group + 每组 100 个 follower",
      "1m、5m、15m、60m 的 Glitch Score",
      "Journal、Metrics + Insights",
      "技术、宏观 + 情绪上下文",
      "Nasdaq + Mag7 增强数据",
      "支持自有指标 + 机器人",
    ],
    homePaidAccessFeatures: [
      "最多 10 个 groups / masters",
      "每组最多 100 个 follower",
      "1m、5m、15m、60m 的 Glitch Score",
      "Journal、Metrics 与 Insights 绩效引擎",
      "行情状态、技术、order-flow、基本面与宏观上下文",
      "Nasdaq + Mag7 增强数据 + 新闻情绪叠加",
      "支持自有指标、策略和机器人",
    ],
    featureLabel: "你将获得",
    pricingPlans: [
      {
        id: "free-tier",
        eyebrow: "免费",
        title: "先从 guardrails 开始",
        description: "先保护账户、验证 workflow，并在付费前把核心助手层跑起来。",
        price: "$0",
        priceSuffix: "起步",
        secondaryPrice: "快速上手",
        note: "快速安装、熟悉 workflow，等操作真正需要更大规模时再升级。",
        ctaLabel: "免费开始",
        ctaKey: "free",
        tone: "neutral",
        features: [
          "手动 + 自动复制",
          "合规 + firm 规则",
          "1 个 master + 2 个 follower",
          "风险控制指标",
          "Replicate + Flatten All",
          "核心助手层",
        ],
      },
      {
        id: "go-pro",
        eyebrow: "月付 / 年付",
        title: "灵活的高级访问",
        description: "解锁完整高级功能栈，计费方式适合活跃交易员与成长中的多账户运营。",
        price: "$95",
        priceSuffix: "/ 月",
        secondaryPrice: "或 $995 / 年",
        note: "在 checkout 中选择月付或年付。高级工具栈保持一致。",
        ctaLabel: "Go Pro",
        ctaKey: "pro",
        tone: "featured",
        badge: "最受欢迎",
        features: [
          "最多 10 个 groups / masters",
          "每组最多 100 个 follower",
          "1m、5m、15m、60m 的 Glitch Score",
          "Journal、Metrics 与 Insights 引擎",
          "Nasdaq、Mag7、macro 与 news sentiment 上下文",
        ],
      },
      {
        id: "lifetime-access",
        eyebrow: "终身访问",
        title: "拥有这层操作系统",
        description: "当你已经确定它是核心基础设施时，可在无持续计费的前提下获得同一套 Glitch 高级功能栈。",
        price: "$2,450",
        priceSuffix: "一次性",
        secondaryPrice: "无持续账单",
        note: "一次付款。完整高级访问。适合构建长期操作栈的交易员。",
        ctaLabel: "获取终身访问",
        ctaKey: "lifetime",
        tone: "premium",
        features: [
          "包含 Monthly / Annual 的全部内容",
          "支持自有指标、策略与机器人",
          "同一套高级合规、复制与分析功能栈",
          "一次性付款而非持续订阅",
          "更适合长期运营者的经济模型",
        ],
      },
    ],
  },
};

export type LocalizedPricingContent = {
  homeFreeTierFeatures: string[];
  homePaidAccessFeatures: string[];
  freeTierPricingFeatures: string[];
  paidAccessComparisonFeatures: string[];
  featureLabel: string;
  pricingPlans: PricingPlan[];
};

function getPricingLocaleKey(locale?: string): keyof typeof pricingContentByLocale {
  if (locale === "pt" || locale === "es" || locale === "fr" || locale === "ru" || locale === "zh") {
    return locale;
  }

  return "en";
}

export function getPricingContent(locale?: string): LocalizedPricingContent {
  const key = getPricingLocaleKey(locale);
  const content = pricingContentByLocale[key];

  return {
    homeFreeTierFeatures: content.homeFreeTierFeatures,
    homePaidAccessFeatures: content.homePaidAccessFeatures,
    freeTierPricingFeatures: content.freeTierPricingFeatures,
    paidAccessComparisonFeatures: content.paidAccessComparisonFeatures,
    featureLabel: content.featureLabel,
    pricingPlans: content.pricingPlans.map((plan) => ({
      ...plan,
      ctaHref:
        plan.ctaKey === "free"
          ? marketingLinks.freeAccessUrl
          : plan.ctaKey === "lifetime"
            ? marketingLinks.lifetimeCheckoutUrl
            : marketingLinks.goProCheckoutUrl,
    })),
  };
}
