#!/usr/bin/env python3
"""One-off v20 data verification + analysis for Glitch247."""
from __future__ import annotations

import re
from pathlib import Path

import numpy as np
import pandas as pd

TELEM = Path(r"C:\Users\alan\Documents\NinjaTrader 8\GlitchData\Telemetry\Glitch247Telemetry20.csv")
EVENTS = Path(r"C:\Users\alan\Documents\NinjaTrader 8\GlitchData\Telemetry\Glitch247TradeEvents20.csv")
TRADES = Path(r"C:\Users\alan\OneDrive\Desktop\Glitch 247 Trades Adaptive v20.csv")
OUT = Path(__file__).resolve().parent.parent / "glitch-247-v20-analysis-autogen.md"


def money(s) -> float:
    if s is None or (isinstance(s, float) and np.isnan(s)):
        return float("nan")
    t = str(s).strip()
    t = re.sub(r"[^\d,.-−]", "", t.replace("−", "-"))
    if not t:
        return float("nan")
    t = t.replace(",", ".")
    if t.count(".") > 1:
        t = t.replace(".", "", t.count(".") - 1)
    try:
        return float(t)
    except ValueError:
        return float("nan")


def play_from_signal(name: str) -> str:
    """Map Glitch247Strategy_{L|S}{L|H}_seq -> LL/LS/HL/HS."""
    if not isinstance(name, str):
        return "UNK"
    m = re.search(r"Glitch247Strategy_([LS])([LH])_", name)
    if not m:
        return "UNK"
    side, conf = m.group(1), m.group(2)
    if side == "L" and conf == "L":
        return "LL"
    if side == "S" and conf == "L":
        return "LS"
    if side == "L" and conf == "H":
        return "HL"
    if side == "S" and conf == "H":
        return "HS"
    return "UNK"


def main() -> None:
    lines: list[str] = []

    lines.append("# Glitch 247 v20 — data verification & analysis\n")
    lines.append("Autogenerated.\n")

    # --- Telemetry ---
    lines.append("## 1) Telemetry (`Glitch247Telemetry20.csv`)\n")
    if not TELEM.exists():
        lines.append("**ERROR**: telemetry file missing.\n")
        OUT.write_text("\n".join(lines), encoding="utf-8")
        return

    head = pd.read_csv(TELEM, nrows=2)
    all_cols = list(head.columns)
    expected = [
        "timestamp",
        "bar_index",
        "tick_size",
        "atr_ticks",
        "adx",
        "primary_direction",
        "fallback_direction",
        "play_type",
        "entry_signal_pass",
        "adx_pass",
        "stop_hard_cap_ticks",
        "adx_min_hl",
        "adx_min_hs",
    ]
    missing = [c for c in expected if c not in all_cols]
    lines.append(f"- Columns: **{len(all_cols)}** (expected extras for simulator: tick_size, trade_date, param snapshot, etc.)\n")
    lines.append(f"- Expected columns present: **{not missing}** {missing}\n")

    nrows = 0
    for ch in pd.read_csv(TELEM, chunksize=400_000, usecols=["timestamp"]):
        nrows += len(ch)
    lines.append(f"- Row count: **{nrows}**\n")

    # Null rate sample (first 800k rows)
    key = [c for c in expected if c in all_cols]
    seen = 0
    nulls = {c: 0 for c in key}
    for ch in pd.read_csv(TELEM, chunksize=200_000, usecols=key):
        seen += len(ch)
        for c in key:
            nulls[c] += ch[c].isna().sum()
        if seen >= 800_000:
            break
    lines.append(f"- Null counts (first ~{seen} rows):\n")
    for c in key:
        lines.append(f"  - `{c}`: {int(nulls[c])}\n")

    t0 = pd.read_csv(TELEM, nrows=1)["timestamp"].iloc[0]
    # last row: read tail via chunked last
    last_ts = None
    for ch in pd.read_csv(TELEM, chunksize=500_000, usecols=["timestamp"]):
        last_ts = ch["timestamp"].iloc[-1]
    lines.append(f"- Time range (first / last): `{t0}` … `{last_ts}`\n")

    # --- Events ---
    lines.append("\n## 2) Trade events (`Glitch247TradeEvents20.csv`)\n")
    if not EVENTS.exists():
        lines.append("**ERROR**: events file missing.\n")
    else:
        ev = pd.read_csv(EVENTS)
        lines.append(f"- Rows: **{len(ev)}**\n")
        lines.append(f"- Columns: **{len(ev.columns)}**\n")
        exp_ev = ["event_seq", "event_type", "play_type", "bar_index_primary", "adx_pass", "adx_min_required"]
        miss_ev = [c for c in exp_ev if c not in ev.columns]
        lines.append(f"- Key columns present: **{not miss_ev}** {miss_ev}\n")
        if "event_type" in ev.columns:
            lines.append("- `event_type` counts:\n```\n")
            lines.append(ev["event_type"].value_counts().to_string())
            lines.append("\n```\n")
        ent = ev[ev["event_type"].astype(str).str.contains("entry", case=False, na=False)]
        lines.append(f"- Rows matching 'entry' in event_type: **{len(ent)}**\n")
        if len(ent) and "play_type" in ent.columns:
            lines.append("- ENTRY `play_type`:\n```\n")
            lines.append(ent["play_type"].value_counts().to_string())
            lines.append("\n```\n")

    # --- Trades ---
    lines.append("\n## 3) Strategy Analyzer trades (`Glitch 247 Trades Adaptive v20.csv`)\n")
    if not TRADES.exists():
        lines.append("**ERROR**: trades file missing.\n")
        OUT.write_text("\n".join(lines), encoding="utf-8")
        return

    tr = pd.read_csv(TRADES, sep=";", engine="python")
    tr["profit_num"] = tr["Profit"].map(money)
    tr["play"] = tr["Entry name"].map(play_from_signal)
    tr["side"] = tr["Market pos."].map(lambda x: str(x).strip().lower() if pd.notna(x) else "")

    lines.append(f"- Rows: **{len(tr)}**\n")
    lines.append(f"- Net PnL (sum Profit): **{tr['profit_num'].sum():,.2f}**\n")
    lines.append(f"- Play type (from entry signal `Glitch247Strategy_{{L|S}}{{L|H}}_`):\n```\n{tr['play'].value_counts().to_string()}\n```\n")

    def exit_bucket(x: str) -> str:
        if not isinstance(x, str):
            return "unknown"
        u = x.upper()
        if "STOP" in u:
            return "stop"
        if "TARGET" in u or "TP" in u:
            return "target"
        if "TIME" in u:
            return "time"
        return "other"

    tr["exit_bucket"] = tr["Exit name"].map(exit_bucket)
    lines.append("- Exit name buckets (heuristic):\n```\n")
    lines.append(tr.groupby("exit_bucket")["profit_num"].agg(["count", "sum"]).to_string())
    lines.append("\n```\n")

    g = tr.groupby(["play", "side"], dropna=False)["profit_num"].agg(["count", "sum", "mean"])
    lines.append("\n### PnL by play × side\n```\n")
    lines.append(g.to_string())
    lines.append("\n```\n")

    long_tr = tr[tr["side"].str.startswith("long", na=False)]
    short_tr = tr[tr["side"].str.startswith("short", na=False)]
    lines.append(f"\n- **Long** total: **{long_tr['profit_num'].sum():,.2f}** (n={len(long_tr)})\n")
    lines.append(f"- **Short** total: **{short_tr['profit_num'].sum():,.2f}** (n={len(short_tr)})\n")

    by_play = tr.groupby("play")["profit_num"].sum().sort_values()
    lines.append("\n### Net by play type (worst → best)\n```\n")
    lines.append(by_play.to_string())
    lines.append("\n```\n")

    # Long-only by play
    lines.append("\n### Long trades only — net by play\n```\n")
    lines.append(long_tr.groupby("play")["profit_num"].agg(["count", "sum"]).to_string())
    lines.append("\n```\n")

    # Join ENTRY events → trades
    lines.append("\n## 4) Events ↔ trades (ENTRY alignment)\n")
    if EVENTS.exists():
        ev = pd.read_csv(EVENTS)
        ev["ts"] = pd.to_datetime(ev["timestamp"], errors="coerce")
        ent = ev[ev["event_type"].astype(str).str.upper().eq("ENTRY")].copy()
        tr2 = tr.copy()
        tr2["entry_ts"] = pd.to_datetime(tr2["Entry time"], errors="coerce")
        tr2["entry_sig"] = tr2["Entry name"].astype(str)

        ent = ent.sort_values("ts")
        tr2 = tr2.sort_values("entry_ts")
        m = pd.merge_asof(
            tr2,
            ent,
            left_on="entry_ts",
            right_on="ts",
            direction="nearest",
            tolerance=pd.Timedelta("3h"),
        )
        ok = m["entry_signal"].fillna("") == m["entry_sig"].fillna("")
        lines.append(f"- merge_asof (3h) exact `entry_signal` match: **{ok.mean()*100:.1f}%**\n")
        if "adx_now" in m.columns:
            sub = m[ok & m["adx_now"].notna()]
            for label, mask in [
                ("long", sub["side"].str.startswith("long", na=False)),
                ("short", sub["side"].str.startswith("short", na=False)),
            ]:
                ssub = sub[mask]
                if len(ssub):
                    lines.append(
                        f"- Median ADX at entry ({label}): **{ssub['adx_now'].median():.1f}** "
                        f"(p25 {ssub['adx_now'].quantile(0.25):.1f}, p75 {ssub['adx_now'].quantile(0.75):.1f})\n"
                    )

    lines.append("\n## 5) Summary\n")
    lines.append("- Telemetry includes bar OHLC, indicators, play/risk columns, and parameter snapshot fields needed for offline sweeps.\n")
    lines.append("- Trade events add per-fill context (`event_seq`, bar indices, ADX gate snapshot).\n")
    lines.append("- Trades export uses `;` separator and locale money strings — parsed for aggregates.\n")

    OUT.write_text("\n".join(lines), encoding="utf-8")
    print(f"Wrote {OUT}")


if __name__ == "__main__":
    main()
