import unittest
from pathlib import Path


ROOT = Path(__file__).resolve().parents[3]
EXECUTOR = ROOT / "ninjatrader/Glitch/AddOns/GlitchAddOn/Services/Ai/GlitchAiOrderExecutor.cs"
COPY_ENGINE = ROOT / "ninjatrader/Glitch/AddOns/GlitchAddOn/Services/Trading/GlitchCopyEngine.cs"
MAIN_WINDOW = ROOT / "ninjatrader/Glitch/AddOns/GlitchAddOn/UI/MainWindow/GlitchMainWindow.cs"
REPLICATION = ROOT / "ninjatrader/Glitch/AddOns/GlitchAddOn/UI/MainWindow/GlitchMainWindow.Replication.partial.cs"
HISTORY = ROOT / "ninjatrader/Glitch/AddOns/GlitchAddOn/Services/Ai/GlitchAiIntentHistoryReader.cs"
FIREWALL = ROOT / "ninjatrader/Glitch/AddOns/GlitchAddOn/Services/Ai/GlitchAiRiskFirewall.cs"
POLICY = ROOT / "ninjatrader/Glitch/AddOns/GlitchAddOn/Services/Ai/GlitchAiRailPolicyStore.cs"
PORTFOLIO = ROOT / "ninjatrader/Glitch/AddOns/GlitchAddOn/Services/Ai/GlitchAiPortfolioSnapshotReader.cs"
PORTFOLIO_CAPTURE = ROOT / "ninjatrader/Glitch/AddOns/GlitchAddOn/UI/MainWindow/GlitchMainWindow.PortfolioSnapshot.partial.cs"
SNAPSHOT = ROOT / "ninjatrader/Glitch/AddOns/GlitchAddOn/Services/Ai/GlitchAiSnapshotRegistry.cs"
MARKET_WRITER = ROOT / "ninjatrader/Glitch/AddOns/GlitchAddOn/Services/Persistence/GlitchMarketSnapshotWriter.cs"
MARKET_RAW_JSON = ROOT / "ninjatrader/Glitch/Indicators/glitch/GlitchMarketSnapshotRawJson.cs"
ANALYTICS_BRIDGE = ROOT / "ninjatrader/Glitch/Indicators/glitch/GlitchAnalyticsBridge.cs"
BRIDGE_COMPAT = ROOT / "ninjatrader/Glitch/Indicators/glitch/GlitchBridgeBusCompat.cs"
ANALYTICS_FEED_BUS = ROOT / "ninjatrader/Glitch/AddOns/GlitchAddOn/UI/Analytics/GlitchAnalyticsFeedBus.cs"
INSTRUMENT_METADATA = ROOT / "ninjatrader/Glitch/AddOns/GlitchAddOn/Services/Trading/GlitchInstrumentMetadataService.cs"
TRADE_INSIGHTS = ROOT / "ninjatrader/Glitch/AddOns/GlitchAddOn/Services/Insights/GlitchTradeInsightsService.cs"
PREFLIGHT = ROOT / "tools/hermes/preflight-open.ps1"
CYCLE = ROOT / "tools/hermes/invoke-hermes-cycle.ps1"
JOURNAL_SYNC = ROOT / "tools/hermes/sync-nt-journal.ps1"
IDEMPOTENCY = ROOT / "tools/hermes/verify-nothing-idempotency.ps1"
SIM_SUBMIT = ROOT / "tools/hermes/submit-validated-sim-intent.ps1"
SIM_EXIT_SUBMIT = ROOT / "tools/hermes/submit-validated-sim-exit.ps1"
FIRST_TRADE_LOOP = ROOT / "tools/hermes/run-first-paper-trade-cycle.ps1"
PAPER_TRADING_LOOP = ROOT / "tools/hermes/run-paper-trading-cycle.ps1"
PORTFOLIO_CYCLE = ROOT / "tools/hermes/invoke-hermes-portfolio-cycle.ps1"
PORTFOLIO_RUNNER = ROOT / "tools/hermes/run-hermes-portfolio-cycle.ps1"
OPPORTUNITY_GATE = ROOT / "tools/hermes/hermes-opportunity-gate.ps1"
MANAGEMENT_GUARD = ROOT / "tools/hermes/run-hermes-management-guard.ps1"
OPPORTUNITY_GUARD = ROOT / "tools/hermes/run-hermes-opportunity-guard.ps1"
SIM_GUARD_TICK = ROOT / "tools/hermes/run-hermes-sim-guard-tick.ps1"
SIM_GUARD_SCHEDULER = ROOT / "tools/hermes/install-hermes-sim-guard-scheduled-task.ps1"
SIM_STATUS = ROOT / "tools/hermes/get-hermes-sim-status.ps1"
BUILD_CAPSULE = ROOT / "tools/hermes/build-data-capsule.ps1"
DIRECT_CYCLE = ROOT / "tools/hermes/run-direct-glitch-cycle.py"
EXCHANGE_WRITER = ROOT / "ninjatrader/Glitch/AddOns/GlitchAddOn/Services/Persistence/GlitchHermesExchangeWriter.cs"
CONTROL_SERVER = ROOT / "ninjatrader/Glitch/AddOns/GlitchAddOn/Services/Ai/GlitchHermesControlServer.cs"
CONTROL_PLUGIN = ROOT / "hermes-profile/plugins/glitch-control/__init__.py"
DIRECT_INSTALLER = ROOT / "tools/hermes/install-direct-hermes-bridge.ps1"
DIRECT_CRON = ROOT / "tools/hermes/enable-direct-hermes-cron.ps1"
TRADING_EPOCH_RESET = ROOT / "tools/hermes/reset-hermes-trading-epoch.ps1"
NAMED_SESSION_RESET = ROOT / "tools/hermes/reset-named-hermes-session.py"


class SourceSafetyContractTests(unittest.TestCase):
    def test_market_snapshot_adds_numeric_analytics_without_opinion_labels(self):
        raw = MARKET_RAW_JSON.read_text(encoding="utf-8")
        writer = MARKET_WRITER.read_text(encoding="utf-8")
        self.assertIn("derived_analytics", raw)
        self.assertIn("directional_score", raw)
        self.assertIn("tradeability_score", raw)
        self.assertIn("DirectionalScore = reading.DirectionalScore", writer)
        self.assertNotIn('"signal_label"', raw)
        self.assertNotIn('"regime_label"', raw)
        self.assertNotIn('"no_trade_reasons"', raw)

    def test_named_trading_session_prompt_can_refresh_without_losing_transcript(self):
        helper = NAMED_SESSION_RESET.read_text(encoding="utf-8")
        self.assertIn('"--refresh-prompt"', helper)
        self.assertIn("db.update_system_prompt(db.resolve_resume_session_id(old_id), None)", helper)
        self.assertIn('"transcript_preserved": not args.apply', helper)

    def test_portfolio_snapshot_top_level_truth_comes_from_serialized_positions(self):
        capture = PORTFOLIO_CAPTURE.read_text(encoding="utf-8")
        self.assertIn("positions = BuildPortfolioSnapshotPositions(account)", capture)
        self.assertIn("positions.Sum(position => position.UnrealizedPnl)", capture)
        self.assertIn("BuildPortfolioPositionDisplay(positions)", capture)
        self.assertIn("TotalPnl = row.RealizedPnlRaw + liveUnrealizedPnl", capture)
        self.assertNotIn("PositionDisplay = row.Position", capture)

    def test_complete_copied_follower_exit_delegates_order_retirement_to_nt_flatten(self):
        copy_engine = COPY_ENGINE.read_text(encoding="utf-8")
        self.assertIn("closableQuantity != int.MaxValue", copy_engine)
        self.assertIn("if (followerQty != closableQuantity)", copy_engine)
        self.assertIn("copy_skip|partial_exit_requires_bracket_resize", copy_engine)
        self.assertIn("result = TryFlattenFollowerInstrument(followerAccount, instrument, out failureReason);", copy_engine)
        self.assertIn("account.Flatten(new[] { instrument });", copy_engine)
        self.assertNotIn("_followerMarketCloseOrders", copy_engine)
        self.assertNotIn("CancelWorkingFollowerProtection", copy_engine)

    def test_ai_follower_entry_requires_signal_keyed_protection_before_copy(self):
        copy_engine = COPY_ENGINE.read_text(encoding="utf-8")
        executor = EXECUTOR.read_text(encoding="utf-8")
        self.assertIn("GroupsBySignal.TryGetValue(entrySignal.Trim()", executor)
        self.assertIn("group.Accounts[0].Name", executor)
        self.assertNotIn("ReferenceEquals(item.Accounts[0], masterAccount)", executor)
        self.assertIn("IsAiEntrySignal(context.OrderSignalName) && !hasProtectionPlan", copy_engine)
        self.assertIn("ai_follower_protection_plan_missing", copy_engine)
        self.assertIn("AiFollowerProtectionMissing", copy_engine)

    def test_master_native_stop_or_target_is_not_copied_over_follower_native_brackets(self):
        copy_engine = COPY_ENGINE.read_text(encoding="utf-8")
        main_window = MAIN_WINDOW.read_text(encoding="utf-8")
        process_master = copy_engine.split("public void ProcessMasterExecution", 1)[1].split(
            "public void ProcessFollowerOrderUpdate", 1
        )[0]
        internal_signal = main_window.split("private static bool IsReplicationInternalSignal", 1)[1].split(
            "private void TryAppendRuntimeEventJournalEntry", 1
        )[0]
        self.assertIn("|| IsAiProtectionSignal(context.OrderSignalName)", process_master)
        self.assertNotIn("GlitchAiOrderExecutor.SignalStop", internal_signal)
        self.assertNotIn("GlitchAiOrderExecutor.SignalTarget", internal_signal)
        self.assertIn("SubmitCopyWithRetry", process_master)
        self.assertIn("closableQuantity != int.MaxValue", process_master)
        self.assertIn("TryFlattenFollowerInstrument", copy_engine)

    def test_flatten_all_never_treats_unresolved_configured_accounts_as_flat(self):
        main_window = MAIN_WINDOW.read_text(encoding="utf-8")
        replication = REPLICATION.read_text(encoding="utf-8")
        self.assertIn("ResolveFlattenAllAccounts(out List<string> unresolvedAccounts)", main_window)
        self.assertIn("unresolved_or_disconnected", main_window)
        self.assertIn("bool complete = flattened && unresolvedAccounts.Count == 0", main_window)
        self.assertIn("Flatten All could not positively resolve any accounts", main_window)
        self.assertIn("var configuredNames = new HashSet<string>", replication)
        self.assertIn("unresolvedConfiguredAccounts.Add(accountName)", replication)

    def test_direct_control_is_authenticated_idempotent_and_glitch_owned(self):
        server = CONTROL_SERVER.read_text(encoding="utf-8")
        plugin = CONTROL_PLUGIN.read_text(encoding="utf-8")
        installer = DIRECT_INSTALLER.read_text(encoding="utf-8")
        firewall = FIREWALL.read_text(encoding="utf-8")
        self.assertIn('BindAddress = "http://127.0.0.1:8789/"', server)
        self.assertIn("GlitchRailBearerAuth.IsAuthorized", server)
        self.assertIn("HasCommandId(commandId)", server)
        self.assertIn('action == "FLATTEN_ALL"', server)
        self.assertIn('action == "TRADING_OFF" || action == "TRADING_ON"', server)
        self.assertIn('"hermes_trading_paused"', firewall)
        self.assertIn('string.Equals(policy.Mode, "paper"', EXECUTOR.read_text(encoding="utf-8"))
        self.assertNotIn('"max_trades_per_day"', firewall)
        self.assertNotIn('"cooldown_active"', firewall)
        self.assertIn("find_gateway_pids", plugin)
        self.assertIn("gateway_windows.is_installed", plugin)
        self.assertIn('"gateway", "start"', plugin)
        self.assertNotIn('"gateway", "run"', plugin)
        self.assertNotIn('getattr(subprocess, "DETACHED_PROCESS", 0)', plugin)
        self.assertIn("gateway install --start-now --start-on-login", installer)
        direct_cycle = DIRECT_CYCLE.read_text(encoding="utf-8")
        self.assertIn('"chat", "-Q",', direct_cycle)
        self.assertIn('"--resume", "trading",', direct_cycle)
        self.assertNotIn('"-z",', direct_cycle)
        self.assertIn('"trade-mode"', plugin)
        self.assertIn('"pause-trading"', plugin)
        self.assertIn('"long"', plugin)
        self.assertIn('"short"', plugin)
        self.assertIn("_require_flat_paper_group", plugin)
        self.assertIn('resume_job(job["id"])', plugin)
        self.assertIn("Glitch's ON/OFF state is the operator-facing authority", plugin)
        self.assertIn("ctx.register_command", plugin)
        self.assertIn("ensure-named-sessions.py", installer)
        self.assertIn("plugins enable glitch-control", installer)

    def test_direct_exchange_has_single_writer_boundaries_and_no_codex_loop(self):
        exchange = EXCHANGE_WRITER.read_text(encoding="utf-8")
        cycle = DIRECT_CYCLE.read_text(encoding="utf-8")
        self.assertIn('Path.Combine(GetExchangeRoot(), "glitch", relativePath)', exchange)
        self.assertIn('exchange / "hermes" / "outbox"', cycle)
        self.assertIn('exchange / "hermes" / "receipts"', cycle)
        self.assertIn('"chat", "-Q",', cycle)
        self.assertIn('"--resume", "trading",', cycle)
        self.assertNotIn('"-z",', cycle)
        self.assertNotIn('"--continue",', cycle)
        self.assertNotIn('command.remove("--continue")', cycle)
        self.assertIn('os.O_CREAT | os.O_EXCL | os.O_WRONLY', cycle)
        self.assertIn('if not packet_is_current(packet):', cycle)
        self.assertIn('"http://127.0.0.1:8788/intent"', cycle)
        self.assertIn("TryWriteDecisionPacket(minuteUtc, minuteDirectory);", exchange)
        self.assertNotIn("minuteUtc.Minute % FramesPerPacket", exchange)

    def test_direct_cycle_has_no_paper_trade_count_or_cooldown_gate(self):
        cycle = DIRECT_CYCLE.read_text(encoding="utf-8")
        self.assertIn("no daily trade-count quota", cycle)
        self.assertIn("no deterministic cooldown", cycle)
        self.assertIn("aspirational daily range", cycle)
        self.assertIn("stay with the thesis or exit", cycle)
        self.assertIn("Use the top-level key decisions, never intents", cycle)
        self.assertIn("strict JSON parser can load", cycle)
        self.assertIn("directive_type=forced_entry", cycle)
        self.assertIn("native brackets are catastrophe", cycle)

    def test_entries_and_exits_require_complete_ai_owned_native_protection(self):
        text = EXECUTOR.read_text(encoding="utf-8")
        self.assertIn("HasCompleteAiProtection(account, instrument, out _)", text)
        self.assertIn("existing_position_not_fully_ai_protected", text)
        self.assertIn("group_exit_not_fully_ai_owned", text)
        self.assertIn("account.Flatten(new[] { group.Instrument })", text)

    def test_multi_tranche_follower_protection_is_correlation_keyed(self):
        text = COPY_ENGINE.read_text(encoding="utf-8")
        self.assertIn("BuildFollowerProtectionKey(followerAccount, instrument, plan.Correlation)", text)
        self.assertIn("TryFindFollowerProtectionTicketUnsafe", text)
        self.assertIn("ReferenceEquals(item.Value.EntryOrder, entryOrder)", text)

    def test_move_stop_uses_native_account_change_and_only_tightens_owned_stops(self):
        text = EXECUTOR.read_text(encoding="utf-8")
        self.assertIn('string.Equals(action, "MOVE_STOP"', text)
        self.assertIn("order.StopPriceChanged = stopPrice", text)
        self.assertIn("accountChanges.Key.Change(orders.ToArray())", text)
        self.assertIn("bool tightens = isLong ? stopPrice > stop.StopPrice : stopPrice < stop.StopPrice", text)
        self.assertIn("GlitchCopyEngine.CopySignalName + \"-S-\"", text)

    def test_user_defined_contract_and_per_contract_risk_are_the_paper_invariants(self):
        policy = POLICY.read_text(encoding="utf-8")
        firewall = FIREWALL.read_text(encoding="utf-8")
        executor = EXECUTOR.read_text(encoding="utf-8")
        self.assertIn("MaxContracts { get; set; } = 5", policy)
        self.assertIn("MaxRiskPerContractUsd { get; set; } = 80", policy)
        self.assertIn("MaxGroupLossPerTradeUsd { get; set; } = 0", policy)
        self.assertIn("MaxDailyLossUsd { get; set; } = 0", policy)
        self.assertIn("max_risk_per_contract_exceeded", firewall)
        self.assertIn("policy.MaxDailyLossUsd > 0", firewall)
        self.assertIn("policy.MaxGroupLossPerTradeUsd > 0", executor)

    def test_trading_mode_is_the_only_operational_gate(self):
        text = FIREWALL.read_text(encoding="utf-8")
        executor = EXECUTOR.read_text(encoding="utf-8")
        self.assertNotIn("if (policy.AiKillSwitch)", text)
        self.assertNotIn("if (!policy.AiEnabled)", text)
        self.assertIn('"hermes_trading_paused"', text)
        self.assertNotIn("policy.ExecutorEnabled", executor)
        sim_status = SIM_STATUS.read_text(encoding="utf-8")
        self.assertIn("control-state.json", sim_status)
        self.assertNotIn("[bool]$policy.executor_enabled", sim_status)

    def test_tracked_orders_use_explicit_terminal_states(self):
        text = EXECUTOR.read_text(encoding="utf-8")
        self.assertIn("group.Orders.All(IsTerminalTrackedOrder)", text)
        self.assertIn("IsAccountRecoveryTerminal", text)
        self.assertIn("GlitchReplicationEngine.IsAccountFlat(account) && allOrdersTerminal", text)
        self.assertIn("order.OrderState == OrderState.Cancelled", text)
        self.assertIn("order.OrderState == OrderState.Rejected", text)

    def test_firewall_and_preflight_fail_closed_on_portfolio_state(self):
        firewall = FIREWALL.read_text(encoding="utf-8")
        preflight = PREFLIGHT.read_text(encoding="utf-8")
        self.assertIn("TryGetFreshRiskState", firewall)
        self.assertIn("TryGetOpenPositionQuantityFromAccountBlock", firewall)
        self.assertIn("portfolio_snapshot_invalid", firewall)
        self.assertIn("portfolio_fresh", preflight)
        self.assertIn("executor_group_portfolio_fields_complete", preflight)
        self.assertIn("$market.created_utc", preflight)
        self.assertIn("$mnq.timestamp_utc", preflight)
        self.assertIn("mnq_timeframes_fresh", preflight)
        self.assertIn("$bar.utc_time", preflight)
        self.assertIn("executor_group_accounts_unique", preflight)
        self.assertIn("executor_group_ratios_valid", preflight)
        self.assertIn("max_risk_per_contract_by_group_usd", preflight)

    def test_non_entry_actions_are_not_blocked_by_entry_snapshot_freshness(self):
        firewall = FIREWALL.read_text(encoding="utf-8")
        policy = (ROOT / "ninjatrader/Glitch/AddOns/GlitchAddOn/Services/Ai/GlitchAiRailPolicyStore.cs").read_text(encoding="utf-8")
        self.assertIn("06_snapshot_freshness:not_required_for_non_entry", firewall)
        self.assertIn("15_compliance:pass_risk_reducing_or_noop", firewall)
        self.assertLess(firewall.index("if (!isEnter)"), firewall.index("if (isEnter)\n            {\n                double tradeRiskUsd"))
        self.assertIn("SnapshotMaxAgeSeconds { get; set; } = 180", policy)
        self.assertIn('"snapshot_max_age_seconds\\\":180', policy)

    def test_positions_parser_rejects_non_object_members(self):
        text = PORTFOLIO.read_text(encoding="utf-8")
        self.assertIn("if (positionsArray[index] != '{')", text)
        self.assertIn("if (positionsArray[index] != ',')", text)

    def test_production_cycle_has_timeout_and_failure_journal(self):
        text = CYCLE.read_text(encoding="utf-8")
        self.assertIn("HermesTimeoutSeconds", text)
        self.assertIn("WaitForExit($TimeoutSeconds * 1000)", text)
        self.assertIn("glitch.hermes.cycle_journal.v1", text)
        self.assertIn("Write-CycleJournal -Status 'failed'", text)
        self.assertIn("Remove-Item -LiteralPath $active", text)

    def test_nt_journals_are_synced_verbatim_before_inference(self):
        cycle = CYCLE.read_text(encoding="utf-8")
        sync = JOURNAL_SYNC.read_text(encoding="utf-8")
        self.assertLess(cycle.index("sync-nt-journal.ps1"), cycle.index("$modelCycle = [ordered]@{"))
        self.assertIn("Copy-Item -LiteralPath $from", sync)
        self.assertIn("'received.jsonl' = 'intents\\received.jsonl'", sync)
        self.assertIn("'decisions.jsonl' = 'intents\\decisions.jsonl'", sync)
        self.assertIn("'executions.jsonl' = 'intents\\executions.jsonl'", sync)
        self.assertIn("'tradeledger.tsv' = 'tradeledger.tsv'", sync)
        self.assertIn("'Journal.tsv' = 'Journal.tsv'", sync)
        self.assertIn("hermes-cycles*.jsonl", sync)
        self.assertIn("profile_filter = $Profile", cycle)
        self.assertIn("account_filter = $MasterAccount", cycle)
        self.assertIn("decision_audit", cycle)

    def test_snapshot_hash_freshness_and_market_price_are_bound_to_one_read(self):
        firewall = FIREWALL.read_text(encoding="utf-8")
        executor = EXECUTOR.read_text(encoding="utf-8")
        snapshot = SNAPSHOT.read_text(encoding="utf-8")
        self.assertIn("TryGetFreshInstrumentPrice", firewall)
        self.assertIn("TryGetFreshInstrumentPrice", executor)
        self.assertIn("string json = File.ReadAllText(path);", snapshot)
        self.assertIn("snapshot_hash_mismatch", snapshot)
        self.assertIn("snapshot_price_missing", snapshot)
        self.assertNotIn("TryGetInstrumentPrice(instrument, out entry)", firewall)
        self.assertIn("TryReadSnapshotByHash", snapshot)
        self.assertIn("GetRecentSnapshotPath(snapshotHash)", snapshot)
        writer = MARKET_WRITER.read_text(encoding="utf-8")
        self.assertIn("WriteRecentSnapshot(hash, json)", writer)
        self.assertIn("for (int i = 5; i < recent.Length; i++)", writer)

    def test_live_snapshot_writer_supplies_firewall_current_price_contract(self):
        writer = MARKET_WRITER.read_text(encoding="utf-8")
        raw_json = MARKET_RAW_JSON.read_text(encoding="utf-8")
        feed_bus = ANALYTICS_FEED_BUS.read_text(encoding="utf-8")
        bridge = ANALYTICS_BRIDGE.read_text(encoding="utf-8")
        compat = BRIDGE_COMPAT.read_text(encoding="utf-8")
        executor = EXECUTOR.read_text(encoding="utf-8")
        snapshot = SNAPSHOT.read_text(encoding="utf-8")
        cache = (ROOT / "ninjatrader/Glitch/AddOns/GlitchAddOn/Services/Persistence/GlitchAnalyticsBridgeCacheStore.cs").read_text(encoding="utf-8")
        self.assertIn("CurrentPrice = snapshot.CurrentPrice", writer)
        self.assertIn("public double? CurrentPrice { get; set; }", raw_json)
        self.assertIn('"\\\"current_price\\\":" + JsonNullableNumber(snapshot.CurrentPrice)', raw_json)
        self.assertIn("InstrumentFullName = snapshot.InstrumentFullName", writer)
        self.assertIn("public string InstrumentFullName { get; set; }", raw_json)
        self.assertIn('"\\\"instrument_full_name\\\":" + JsonString(snapshot.InstrumentFullName)', raw_json)
        self.assertIn("InstrumentFullName = Instrument == null ? null : Instrument.FullName", bridge)
        self.assertIn('SetProperty(message, "InstrumentFullName"', compat)
        self.assertIn("state.InstrumentFullName = normalizedReading.InstrumentFullName", feed_bus)
        self.assertIn("InstrumentFullName = state.InstrumentFullName", feed_bus)
        self.assertIn("public string InstrumentFullName { get; set; }", cache)
        self.assertIn("TryGetInstrumentFullName", snapshot)
        self.assertIn("RegisterTradeInstrument(snapshotInstrumentFullName)", executor)

    def test_analytics_bridge_periodically_repairs_dated_trade_contract_registration(self):
        text = ANALYTICS_BRIDGE.read_text(encoding="utf-8")
        compat = BRIDGE_COMPAT.read_text(encoding="utf-8")
        feed_bus = ANALYTICS_FEED_BUS.read_text(encoding="utf-8")
        periodic = text.split("(nowUtc - _lastBootstrapRegisterUtc) >= TimeSpan.FromSeconds(5)", 1)[1]
        periodic = periodic.split("int minutes = ResolveMinutesForBip", 1)[0]
        self.assertIn("RegisterTradeInstrumentInstance(Instrument)", periodic)
        self.assertIn("RegisterTradeInstrumentInstance", compat)
        self.assertIn("instrument as NinjaTrader.Cbi.Instrument", feed_bus)
        self.assertIn("RegisterBridgeBootstrapPublisher", periodic)

    def test_active_archetype_measurements_reach_live_market_snapshot(self):
        bridge = ANALYTICS_BRIDGE.read_text(encoding="utf-8")
        compat = BRIDGE_COMPAT.read_text(encoding="utf-8")
        feed = ANALYTICS_FEED_BUS.read_text(encoding="utf-8")
        writer = MARKET_WRITER.read_text(encoding="utf-8")
        raw = MARKET_RAW_JSON.read_text(encoding="utf-8")
        for field in ("Open", "High", "Low", "Volume"):
            self.assertIn(f"public double? {field}", compat)
            self.assertIn(f'SetProperty(message, "{field}"', compat)
            self.assertIn(f"public double? {field}", feed)
            self.assertIn(f"reading.{field} = ReadLegacyNullableDouble", feed)
            self.assertIn(f"{field} = reading.{field}", writer)
            self.assertIn(f"public double? {field}", raw)
            self.assertIn(f"{field} = {field}s[bip][0]", bridge)
        for field in ("DiPlus", "DiMinus", "Cci", "MacdHistogram"):
            self.assertIn(f"public double? {field}", compat)
            self.assertIn(f'SetProperty(message, "{field}"', compat)
            self.assertIn(f"public double? {field}", feed)
            self.assertIn(f"reading.{field} = ReadLegacyNullableDouble", feed)
            self.assertIn(f"{field} = reading.{field}", writer)
            self.assertIn(f"public double? {field}", raw)
        self.assertIn("DiPlus = diPlus", bridge)
        self.assertIn("DiMinus = diMinus", bridge)
        self.assertIn("Cci = cci", bridge)
        self.assertIn("MacdHistogram = macdHistogramValue", bridge)

    def test_analytics_freshness_cannot_be_advanced_by_stale_chart_replay(self):
        bridge = ANALYTICS_BRIDGE.read_text(encoding="utf-8")
        feed = ANALYTICS_FEED_BUS.read_text(encoding="utf-8")
        self.assertIn("State == State.Realtime", bridge)
        self.assertIn("TryGetFreshPrimaryBarUtc(nowUtc, out primaryBarUtc)", bridge)
        self.assertIn("BootstrapPrimaryMaxAge = TimeSpan.FromMinutes(3)", bridge)
        self.assertIn("primary 1-minute bar is missing or stale", bridge)
        self.assertIn("UtcTime = nowUtc", bridge)
        self.assertIn("DateTime readingUtc = DateTime.UtcNow", bridge)
        self.assertIn("NormalizeUtcTimestamp", feed)
        self.assertIn("DateTime.SpecifyKind(value, DateTimeKind.Utc)", feed)
        self.assertIn("normalized > nowUtc.AddMinutes(5)", feed)

    def test_bridge_rebinds_to_active_addon_assembly_after_compile(self):
        text = BRIDGE_COMPAT.read_text(encoding="utf-8")
        self.assertIn('TelemetryServerTypeFullName = "Glitch.Services.Ai.GlitchExternalTelemetryServer"', text)
        self.assertIn("IsActiveAddOnAssembly(assembly)", text)
        self.assertIn('GetProperty(\n                    "IsRunning"', text)
        self.assertIn("for (int i = assemblies.Length - 1; i >= 0; i--)", text)
        retry_gate = text.index("(nowUtc - _lastResolveUtc) < ResolveRetryInterval")
        preferred = text.index("Type busType = ResolvePreferredBusType()")
        self.assertLess(retry_gate, preferred)

    def test_executor_never_falls_back_to_generic_futures_root(self):
        metadata = INSTRUMENT_METADATA.read_text(encoding="utf-8")
        executor = EXECUTOR.read_text(encoding="utf-8")
        self.assertIn("if (string.Equals(instrumentRoot.Trim(), root", metadata)
        self.assertIn("TryResolveKnownMicroIndexFrontContract(root, DateTime.UtcNow", metadata)
        self.assertIn("MNQ", metadata)
        self.assertIn("MES", metadata)
        self.assertIn("M2K", metadata)
        self.assertIn("GetEquityIndexFrontContractSuffix", metadata)
        self.assertIn("GetThirdFriday(year, month).AddDays(-8)", metadata)
        self.assertIn("IsConcreteTradeInstrument(instrument, root)", metadata)
        self.assertIn("!string.Equals(instrument.FullName.Trim(), root.Trim()", metadata)
        self.assertIn("TryGetInstrumentFullName(snapshotHash, instrumentRoot", executor)
        self.assertIn("TryGetFreshExecutionPrice(instrument, DateTime.UtcNow", executor)
        self.assertIn("ExecutionPriceMaxAge = TimeSpan.FromSeconds(5)", executor)
        self.assertIn('"|contract=" + CleanToken(instrument.FullName)', executor)

    def test_executor_treats_sim101_quantity_as_group_master_quantity(self):
        text = EXECUTOR.read_text(encoding="utf-8")
        self.assertIn('GlitchStateStore.GetDefaultPath("AccountGroups.tsv")', text)
        self.assertIn("GlitchStateStore.LoadAccountGroups(groupPath)", text)
        self.assertIn("new ConfiguredGroupMember { AccountName = selected.MasterAccount.Trim(), Ratio = 1d }", text)
        self.assertIn("double scaledQuantity = masterQuantity * member.Ratio;", text)
        self.assertIn("double groupRisk = members.Sum(member => perContractRisk * member.Quantity);", text)
        self.assertIn("double accountRisk = perContractRisk * member.Quantity;", text)
        self.assertIn('"|master_quantity=" + masterMember.Quantity', text)
        self.assertIn('"|expected_accounts=" + string.Join', text)
        self.assertIn('"|replication_owner=GlitchCopyEngine"', text)
        self.assertIn("Accounts = new List<Account> { masterMember.Account }", text)
        self.assertNotIn('"|qty_each="', text)

    def test_recurring_paper_loop_is_fail_closed_and_one_shot_armed(self):
        text = PAPER_TRADING_LOOP.read_text(encoding="utf-8")
        self.assertIn("(Join-Path $PSScriptRoot 'preflight-open.ps1')", text)
        self.assertIn("if ($MasterAccount) { $preflightArgs +=", text)
        self.assertIn("paper_preflight_not_ready", text)
        self.assertIn("(Join-Path $PSScriptRoot 'invoke-hermes-cycle.ps1')", text)
        self.assertIn("'-Profile', $Profile", text)
        self.assertIn("submit-validated-sim-intent.ps1", text)
        self.assertNotIn("executor_enabled", text)
        self.assertNotIn("policy.json", text)

    def test_ai_entries_use_copy_engine_without_copying_follower_internal_orders(self):
        executor = EXECUTOR.read_text(encoding="utf-8")
        main_window = MAIN_WINDOW.read_text(encoding="utf-8")
        replication = REPLICATION.read_text(encoding="utf-8")
        copy_engine = COPY_ENGINE.read_text(encoding="utf-8")
        self.assertIn('SignalEntry = "GLT-AI-E"', executor)
        self.assertIn("if (IsReplicationInternalSignal(signalName))", replication)
        self.assertIn('CopySignalName = "GLT-COPY"', copy_engine)
        self.assertIn("follower_has_no_closable_exposure", copy_engine)
        self.assertIn("context.Action == OrderAction.BuyToCover", copy_engine)
        self.assertIn("context.Action == OrderAction.Sell", copy_engine)
        self.assertIn("Math.Min(followerQty, closableQuantity)", copy_engine)
        self.assertIn("TryGetReplicationProtection", copy_engine)
        self.assertIn("SubmitFollowerProtection", copy_engine)
        self.assertIn("follower_protection|instrument=", copy_engine)
        self.assertIn("follower_structural_brackets_submitted", copy_engine)
        self.assertIn("follower_trade_closed", copy_engine)
        self.assertIn("TryFlattenFollowerInstrument", copy_engine)
        self.assertIn("account.Flatten(new[] { instrument })", copy_engine)
        self.assertIn("_activeFollowerProtectionByKey", copy_engine)
        self.assertIn("TryBuildCatchUpProtectionPlan", copy_engine)
        self.assertIn("CatchUpProtectionMissing", copy_engine)
        self.assertIn("UseAbsolutePrices", copy_engine)
        self.assertIn("replication_owner=GlitchCopyEngine", executor)

    def test_direct_cron_is_single_core_no_agent_path(self):
        text = DIRECT_CRON.read_text(encoding="utf-8")
        self.assertIn("* * * * *", text)
        self.assertIn("--no-agent", text)
        self.assertIn("cron pause", text)
        self.assertIn("cron resume", text)
        self.assertIn("non_core_jobs_disabled", text)
        cycle = DIRECT_CYCLE.read_text(encoding="utf-8")
        self.assertIn("if not trading_runtime_enabled(glitch_data):", cycle)
        self.assertIn("should_invoke_luna", cycle)
        self.assertIn("previous_batch_requests_minute_review", cycle)

    def test_startup_reconciles_all_enabled_followers_identically(self):
        main_window = MAIN_WINDOW.read_text(encoding="utf-8")
        replication = REPLICATION.read_text(encoding="utf-8")
        self.assertIn('AlignAllEnabledFollowersToMaster("startup")', main_window)
        self.assertIn('replication_restored|origin=startup|catchup=applied', main_window)
        self.assertNotIn("AlignAllEnabledSimFollowersToMaster", replication)
        self.assertIn("member.IsMasterRow", replication)

    def test_group_recovery_and_execution_evidence_are_idempotent(self):
        text = EXECUTOR.read_text(encoding="utf-8")
        replication = REPLICATION.read_text(encoding="utf-8")
        self.assertIn("if (!firstRecovery)", text)
        self.assertIn("RecoveryUnresolvedRecorded", text)
        self.assertIn("RecoveryTerminalRecorded", text)
        self.assertIn("RecoveryFlattenSubmitted", text)
        self.assertIn("TryRecoverLateFill", text)
        self.assertIn("ProcessAccountStateUpdate", text)
        self.assertIn("GlitchAiOrderExecutor.ProcessAccountStateUpdate(account)", replication)
        self.assertIn("recordEntryFilled", text)
        self.assertIn("recordOpenProtected", text)
        self.assertIn("recordTradeClosed", text)

    def test_execution_preserves_structural_bracket_and_revalidates_fill_geometry(self):
        text = EXECUTOR.read_text(encoding="utf-8")
        self.assertIn("instrument.MarketData.Last", text)
        self.assertIn("ExecutionPriceMaxAge", text)
        self.assertIn("re-anchor them to the executable price", text)
        self.assertNotIn("group_execution_too_near_invalidation", text)
        self.assertNotIn("group_execution_reward_risk_degraded", text)
        self.assertIn("stopDistance * metadata.PointValue", text)
        self.assertIn("fillPrice - leg.StopDistance", text)
        self.assertIn("masterMember.Account.Submit(new[] { entryOrder })", text)
        self.assertIn("TrySubmitStructuralProtection", text)
        self.assertIn("fillPrice + leg.StopDistance", text)
        self.assertIn("fillPrice - leg.TargetDistance", text)
        self.assertIn("group.ProtectionLegs.Sum(leg => leg.Quantity) != entry.Filled", text)
        self.assertIn("account.Submit(createdOrders.ToArray())", text)
        self.assertIn("BuildSignalName(SignalStop, group.Correlation, accountIndex, legIndex)", text)
        self.assertIn("group_structural_brackets_submitted", text)
        self.assertIn("group_partial_entry_fill_recovery", text)
        self.assertNotIn("group_structural_reward_risk_degraded_at_fill", text)
        self.assertNotIn("minimumSubmissionRewardRisk", text)
        self.assertNotIn("minimumFillRewardRisk", text)
        self.assertIn("HasExactEntryExposure(group, group.Accounts.IndexOf(account))", text)
        self.assertIn("group.EntrySubmissionStarted[0] = true", text)
        self.assertIn("master_submit_recovery_started", text)
        self.assertIn("(!entrySubmissionStarted || IsTerminalTrackedOrder(entry))", text)
        self.assertIn("Take(group.ProtectionLegs.Count * 2)", text)
        self.assertIn("(!entryHasFill || recoveryFlattenSubmitted)", text)
        self.assertNotIn("account.Submit(accountOrders)", text)

    def test_two_leg_replication_uses_distinct_oco_pairs_and_scaled_quantities(self):
        replication = COPY_ENGINE.read_text(encoding="utf-8")
        self.assertIn("plan.Legs.Sum(leg => leg.MasterQuantity)", replication)
        self.assertIn("double ratio = (double)entryOrder.Filled / masterQuantity", replication)
        self.assertIn("double scaledLegQuantity = leg.MasterQuantity * ratio", replication)
        self.assertIn('string oco = "GLTCP" + legSuffix', replication)
        self.assertIn("ticket.Account.Submit(orders.ToArray())", replication)
        self.assertIn("active.LegIndex", replication)
        self.assertIn("FollowerProtectionPartialFill", replication)

    def test_journal_reversal_commission_is_allocated_once(self):
        insights = TRADE_INSIGHTS.read_text(encoding="utf-8")
        self.assertIn("closeQty / executionQuantity", insights)
        self.assertIn("remainder / executionQuantity", insights)
        self.assertIn("Math.Abs(commission) * Math.Min(1d, fraction)", insights)

    def test_known_micro_index_point_values_are_guardrailed(self):
        text = INSTRUMENT_METADATA.read_text(encoding="utf-8")
        self.assertIn("TryResolveKnownMicroIndexMetadata", text)
        self.assertIn('string.Equals(normalizedRoot, "MNQ"', text)
        self.assertIn("expectedPointValue = 2.0d", text)
        self.assertIn('string.Equals(normalizedRoot, "MES"', text)
        self.assertIn('string.Equals(normalizedRoot, "M2K"', text)
        self.assertIn("expectedPointValue = 5.0d", text)
        self.assertIn("Math.Abs(ntPointValue - expectedPointValue)", text)

    def test_idempotency_harness_is_nothing_only_and_unarmed(self):
        text = IDEMPOTENCY.read_text(encoding="utf-8")
        self.assertIn("action -ne 'NOTHING'", text)
        self.assertIn("executor_enabled", text)
        self.assertIn("duplicateStatus -ne 409", text)
        self.assertIn("Locally rebound NOTHING snapshot was superseded before idempotency POST", text)
        self.assertIn("local_endpoint_fixture_from_validated_hermes_nothing", text)
        self.assertIn("expected_actions = @('NOTHING')", text)

    def test_sim_submitter_requires_exact_fresh_validated_master_entry(self):
        text = SIM_SUBMIT.read_text(encoding="utf-8")
        self.assertIn("ENTER_LONG','ENTER_SHORT", text)
        self.assertIn("one MNQ master contract and an operator_profile", text)
        self.assertIn("Validated entry snapshot is not retained by Glitch; executor remains unarmed.", text)
        self.assertIn("Validated entry snapshot expired during arm; no POST performed.", text)
        self.assertIn("if ($candidate.status -eq 'failed')", text)
        self.assertIn("Execution evidence: $($executionFailure.code)", text)
        self.assertIn("$policy.mode = 'sim'", text)
        self.assertIn("$policy.executor_enabled = $true", text)
        self.assertIn("$originalPolicyJson", text)
        self.assertIn("One-shot arm", text)
        self.assertIn("executor_left_armed = $false", text)
        self.assertIn("group_entry_open_protected", text)
        self.assertIn("filled positions with working brackets within 45 seconds", text)
        self.assertIn("Move-Item -LiteralPath $restoreTemp -Destination $policyPath -Force", text)
        self.assertIn("sim-submit.lock", text)

    def test_profile_identity_is_bound_to_exact_group_master(self):
        policy = POLICY.read_text(encoding="utf-8")
        firewall = FIREWALL.read_text(encoding="utf-8")
        executor = EXECUTOR.read_text(encoding="utf-8")
        preflight = PREFLIGHT.read_text(encoding="utf-8")
        cycle = CYCLE.read_text(encoding="utf-8")
        self.assertIn("ProfileAccountBindings", policy)
        self.assertIn('{ "glitch", "Sim101" }', policy)
        self.assertNotIn('"glitch-aggressive", "Sim201"', policy)
        self.assertIn("profile_account_mismatch", firewall)
        self.assertIn("TryResolveProfileAccount", executor)
        self.assertIn("requested_master_matches_profile", preflight)
        self.assertIn("@($profileBindings.Values)", preflight)
        self.assertIn("operator_profile = $Profile", cycle)

    def test_single_account_groups_are_valid_execution_groups(self):
        executor = EXECUTOR.read_text(encoding="utf-8")
        preflight = PREFLIGHT.read_text(encoding="utf-8")
        self.assertNotIn("executor_group_has_no_enabled_followers", executor)
        self.assertNotIn("executor_group_has_enabled_followers", preflight)

    def test_single_operator_portfolio_batch_is_route_isolated_and_unarmed(self):
        cycle = PORTFOLIO_CYCLE.read_text(encoding="utf-8")
        runner = PORTFOLIO_RUNNER.read_text(encoding="utf-8")
        self.assertIn("operator.json", cycle)
        self.assertIn("glitch.hermes.portfolio_cycle.v1", cycle)
        self.assertIn("validate_intent_batch.py", cycle)
        self.assertIn("Normalize-HermesBatchJson -Path $outputPath", cycle)
        self.assertIn("[string]$NormalizeBatchPath", cycle)
        self.assertIn("glitch.hermes.batch_normalize_result.v1", cycle)
        self.assertIn("Repair-HermesBatchScalarFields", cycle)
        self.assertIn("Convert-HermesFieldToString", cycle)
        self.assertIn("@('route_id','name','profile','operator_profile')", cycle)
        self.assertIn("@('master_account','account','name')", cycle)
        self.assertIn("$trimmed.EndsWith('}]}')", cycle)
        self.assertIn("$candidate = $trimmed.Substring(0, $trimmed.Length - 2) + '}]}'", cycle)
        self.assertIn("status = 'validated_no_submission'", cycle)
        self.assertNotIn("submit-validated-sim-intent.ps1", cycle)
        self.assertIn("[switch]$SubmitSim", runner)
        self.assertIn("submit-validated-sim-intent.ps1", runner)
        self.assertIn("submit-validated-sim-exit.ps1", runner)
        self.assertIn("executor_left_armed", runner)
        self.assertIn("policyAfter.mode -ne 'paper'", runner)
        self.assertIn("one_or_more_book_submissions_blocked", runner)
        self.assertIn("if ($exitCode -ne 0) { exit $exitCode }", runner)
        self.assertIn("'--toolsets', 'clarify'", cycle)
        self.assertIn("CURRENT_CYCLE=", cycle)
        self.assertIn("OUTPUT_CONTRACT:", cycle)
        self.assertIn("final_choice=action", cycle)
        self.assertIn("account/operator_profile must be scalar strings", cycle)
        self.assertIn("never objects", cycle)
        self.assertIn("ENTER_LONG/SHORT require quantity=1", cycle)
        self.assertIn("as action/reason siblings", cycle)
        self.assertIn("Do not use book_id, side, ENTER", cycle)
        self.assertIn("if ([int]$usage.api_calls -ne 1)", cycle)
        self.assertIn("conservative-probe may not cite no exact match", cycle)
        self.assertIn("$promptCycle | ConvertTo-Json", cycle)
        self.assertIn("compact_prompt_cycle = $true", cycle)
        self.assertIn("$promptBooks = @($modelBooks", cycle)
        self.assertIn("style = if ($_.book_id -eq 'aggressive')", cycle)
        self.assertIn("recent_completed_trade_count = $recentCompletedTrades.Count", cycle)
        self.assertIn("[switch]$PromptOnly", cycle)
        self.assertIn("glitch.hermes.portfolio_prompt_preview.v1", cycle)
        self.assertIn("prompt_only_return", cycle)
        self.assertNotIn("Read /opt/glitch-data/tests/active-portfolio-cycle.json", cycle)

    def test_portfolio_cycle_derives_machine_features_and_hard_risk_geometry(self):
        cycle = PORTFOLIO_CYCLE.read_text(encoding="utf-8")
        validator = (ROOT / "tools/hermes/tests/validate_intent_batch.py").read_text(encoding="utf-8")
        self.assertIn("machine_features = $machineFeatures", cycle)
        self.assertIn("archetype_evaluation = $compactArchetypes", cycle)
        self.assertIn("$atrNorm60 = $atr60 / $close1", cycle)
        self.assertIn("$diSpread60 = $diPlus60 - $diMinus60", cycle)
        self.assertIn("sess_range_zone", cycle)
        self.assertIn("points_from_session_low", cycle)
        self.assertIn("points_from_session_high", cycle)
        self.assertIn("support_flush_below_prev_low", cycle)
        self.assertIn("support_reclaim_after_flush", cycle)
        self.assertIn("points_above_prev_low", cycle)
        self.assertIn("Get-BarGeometry", cycle)
        self.assertIn("Get-OptionalNumber", cycle)
        self.assertIn("ohlc_complete", cycle)
        self.assertIn("market_ohlc_gate_active", cycle)
        self.assertIn("-not $marketOhlcGateActive", cycle)
        self.assertIn("candle_1m_close_location", cycle)
        self.assertIn("upper_breakout_acceptance_1m", cycle)
        self.assertIn("failed_upper_breakout_1m", cycle)
        self.assertIn("lower_breakdown_acceptance_1m", cycle)
        self.assertIn("failed_lower_breakdown_1m", cycle)
        self.assertIn("upper_extreme_bear_turn_1m", cycle)
        self.assertIn("lower_extreme_bull_turn_1m", cycle)
        self.assertIn("lower_extreme_bear_continuation_pressure_1m", cycle)
        self.assertIn("lower_extreme_bear_continuation_pressure_5m", cycle)
        self.assertIn("lower_extreme_trend_pullback_short_1m", cycle)
        self.assertIn("$close1 -ge ($sessionHigh - 1.0)", cycle)
        self.assertIn("$close1 -gt $previousHigh", cycle)
        self.assertIn("$close1 -le ($sessionLow + 1.0)", cycle)
        self.assertIn("$close1 -lt $previousLow", cycle)
        self.assertIn("upper_wick_points", cycle)
        self.assertIn("lower_wick_points", cycle)
        self.assertIn("exact_match = ($preconditionsMatched -and $triggersMatched)", cycle)
        self.assertIn("volatilityStopFloorUsd", cycle)
        self.assertIn("minimumEntryRiskUsd", cycle)
        self.assertIn("risk_capacity_below_noise_floor_active", cycle)
        self.assertIn("volatility_stop_floor_usd", cycle)
        self.assertIn("noiseFloorStopPoints", cycle)
        self.assertIn("noise_floor_stop_points", cycle)
        self.assertIn("stop_inside_mnq_noise_floor", validator)
        self.assertIn("bracket_geometry_guidance", cycle)
        self.assertIn("clean-but-tiny stops", cycle)
        self.assertIn("preferred_minimum_reward_risk = 1.55", cycle)
        self.assertIn("minimum_reward_risk = 1.55", cycle)
        self.assertIn("minimum_planned_reward_risk = 1.75", cycle)
        self.assertIn("minimum_planned_reward_risk", validator)
        self.assertIn("reward_risk_below_planned_headroom", validator)
        self.assertIn("short_lower_extreme_without_acceptance_or_headroom", validator)
        self.assertIn("long_lower_extreme_without_support_reclaim", validator)
        self.assertIn('sess_range_zone == "lower_extreme"', validator)
        self.assertIn("lower_breakdown_acceptance < 1.0", validator)
        self.assertIn("points_from_session_low < 30.0", validator)
        self.assertIn("support_reclaim < 1.0", validator)
        self.assertIn("near_support_reclaim < 1.0", validator)
        self.assertIn("points_above_prev_low < 0.0", validator)
        self.assertIn("lower_breakdown_acceptance_1m=$machineFeatures.lower_breakdown_acceptance_1m", cycle)
        self.assertIn("support_reclaim_after_flush=$machineFeatures.support_reclaim_after_flush", cycle)
        self.assertIn("near_support_reclaim_after_flush=$machineFeatures.near_support_reclaim_after_flush", cycle)
        self.assertIn("points_above_prev_low=$machineFeatures.points_above_prev_low", cycle)
        self.assertIn("keep Glitch live-entry headroom", cycle)
        self.assertIn("estimated_risk_below_book_minimum", validator)
        self.assertIn("reward_risk_below_book_minimum", validator)
        self.assertIn("eligible_book_false_cycle_invalid", validator)
        self.assertIn("CURRENT_CYCLE is sole authority", cycle)
        self.assertIn("archetypes are priors, not gates", cycle)
        self.assertIn("Paper discovery is probabilistic, not whitelist-only", cycle)
        self.assertIn("may not cite no exact match", cycle)
        self.assertIn("reason<=20 words", cycle)
        self.assertIn("audit values<=14 words except final_choice", cycle)
        self.assertIn("Compress-HermesDecisionAudit", cycle)
        self.assertIn("Select-Object -First 14", cycle)
        self.assertIn("decision.decision_audit.final_choice = $decision.action", cycle)
        self.assertIn("WriteAllText($Path", cycle)
        self.assertIn("Text.UTF8Encoding($false)", cycle)
        self.assertIn("recent_completed_trade_rows", cycle)
        self.assertIn("recent_hermes_outcomes", cycle)
        self.assertIn("Select-Object -Last 3", cycle)
        self.assertIn("route_outcome_summary", cycle)
        self.assertIn("action_outcome_summary", cycle)
        self.assertIn("current_loss_streak", cycle)
        self.assertIn("stopped_after_mfe_30_count", cycle)
        self.assertIn("profitCaptureTriggerUsd = 30.0", cycle)
        self.assertIn("cap30_legs", cycle)
        self.assertIn("cap30_pnl", cycle)
        self.assertIn("cap30_improve", cycle)
        self.assertIn("cap30_improve quantifies", cycle)
        self.assertIn("Repeated losses need different evidence", cycle)
        self.assertIn("adaptiveEntryRules", cycle)
        self.assertIn("adaptive_entry_rules", cycle)
        self.assertIn("Do not repeat this action from a weak reclaim/fade thesis", cycle)
        self.assertIn("adaptive_entry_rules bind route/action loss controls", cycle)
        self.assertIn("repeating penalized action requires decisive different evidence", cycle)
        self.assertIn("recent_execution_failures", cycle)
        self.assertIn("Convert-ExecutionMessageToObject", cycle)
        self.assertIn("details = $failureDetails", cycle)
        self.assertIn("Execution failures are not trades", cycle)
        self.assertIn("avg_account_mfe_usd", cycle)
        self.assertIn("avg_account_mae_usd", cycle)
        self.assertIn("max_stopped_mfe_usd", cycle)
        self.assertIn("cap30_improve quantifies bankable profit surrendered to stop", cycle)
        self.assertIn("Negative PnL with positive MFE", cycle)
        self.assertIn("outside_structural_bracket=live escaped bracket", cycle)
        self.assertIn("reward_risk_degraded=R:R below minimum", cycle)
        self.assertIn("One outcome is not expectancy proof", cycle)
        self.assertIn('$30-$40 favorable open PnL', cycle)
        self.assertIn("Target feasibility:", cycle)
        self.assertIn("MNQ stop geometry", cycle)
        self.assertIn("ordinary MNQ noise can tag", cycle)
        self.assertIn("stop distance must clear noise_floor_stop_points", cycle)
        self.assertIn("Do not propose tight MNQ stops below noise_floor_stop_points", cycle)
        self.assertIn("0.75-1.5 ATR5", cycle)
        self.assertIn("Location is first-class", cycle)
        self.assertIn("Paper discovery with controlled risk", cycle)
        self.assertIn("conservative may take bounded Sim probes", cycle)
        self.assertIn("NOTHING needs concrete flat-case advantage over bounded probes", cycle)
        self.assertIn("Aggressive/stay_revert may enter early", cycle)
        self.assertIn("Soft triggers: upper_extreme_bear_turn_1m, lower_extreme_bull_turn_1m, lower_extreme_bear_continuation_pressure_1m/5m", cycle)
        self.assertIn("Lower-extreme bearish continuation is permission only", cycle)
        self.assertIn("require headroom, retest, or skip", cycle)
        self.assertIn("Do not chase lower_extreme shorts or upper_extreme longs", cycle)
        self.assertIn("Get-FilledAiEntriesToday", cycle)
        self.assertIn("group_entry_filled", cycle)
        self.assertIn("trades_today", cycle)
        self.assertNotIn("max_trades_per_day", cycle)
        self.assertNotIn("trade_cap_active", cycle)
        self.assertNotIn("cooldown_after_loss_active", cycle)
        self.assertIn("eligible_for_management", cycle)
        self.assertIn("-and -not $ManagementOnly", cycle)
        self.assertIn("'HOLD'; 'EXIT'", cycle)
        self.assertIn("Current unrealized PnL is first-class evidence", cycle)
        self.assertIn("$30-$40 favorable open PnL", cycle)
        self.assertIn("$80-$100 on larger/high-vol trades", cycle)
        self.assertIn("Do not let large favorable excursion become a stop outcome", cycle)
        self.assertIn("Obey allowed_actions", cycle)
        self.assertIn("Invoke-NativeBounded", cycle)
        self.assertIn("Portfolio preflight for $route/$account", cycle)
        self.assertIn("NinjaTrader journal sync", cycle)
        self.assertIn("timed out after $TimeoutSeconds seconds", cycle)
        self.assertIn("Kill($true)", cycle)

        runner = PORTFOLIO_RUNNER.read_text(encoding="utf-8")
        opportunity_gate = OPPORTUNITY_GATE.read_text(encoding="utf-8")
        self.assertIn("reconcile-hermes-outcomes.py", runner)
        self.assertIn("reason='no_eligible_books'", runner)
        self.assertIn("model_calls=0", runner)
        self.assertIn("hermes-opportunity-gate.ps1", runner)
        self.assertIn("Get-HermesOpportunityGate", runner)
        self.assertIn("eligible_books=$entryBooks.Count", runner)
        self.assertIn("if ($ManagementOnly) { $prepareArgs += '-ManagementOnly' }", runner)
        self.assertIn("$invokeArgs += '-ManagementOnly'", runner)
        self.assertIn("-ExpectedSnapshotHash", runner)
        self.assertIn("snapshot_changed_before_inference", runner)
        self.assertIn("expected_snapshot_hash=$expectedSnapshotHash", runner)
        self.assertIn("[string]$PreparationPath", runner)
        self.assertIn("A supplied preparation is entry-only", runner)
        self.assertIn("Supplied Hermes preparation is missing", runner)
        self.assertIn("[string]$ExpectedSnapshotHash", cycle)
        self.assertIn("Snapshot hash changed before inference", cycle)
        self.assertIn("snapshot_hash = $market.snapshot_hash", cycle)
        self.assertIn("Get-HermesOpportunityGate", opportunity_gate)
        self.assertIn("no_actionable_machine_trigger", opportunity_gate)
        self.assertIn("thin_lower_extreme_continuation_no_call", opportunity_gate)
        self.assertIn("unreclaimed_lower_extreme_bull_turn_no_call", opportunity_gate)
        self.assertIn("lower_extreme_bear_continuation_pressure_5m", opportunity_gate)
        self.assertIn("lower_extreme_trend_pullback_short_1m", opportunity_gate)
        self.assertIn("points_to_short_headroom_30", opportunity_gate)
        self.assertIn("minimum_required_short_headroom", opportunity_gate)
        self.assertIn("shortHeadroomExtensionBufferPoints = 4.0", opportunity_gate)
        self.assertIn("short_headroom_extension_buffer_points", opportunity_gate)
        self.assertIn("points_to_short_headroom_required", opportunity_gate)
        self.assertIn("eligible_short_reward_requirements", opportunity_gate)
        self.assertIn("[pscustomobject][ordered]@{", opportunity_gate)
        self.assertGreaterEqual(opportunity_gate.count("[pscustomobject][ordered]@{"), 2)
        self.assertIn("Measure-Object required_short_headroom_points -Minimum", opportunity_gate)
        self.assertIn("lower_extreme_continuation_insufficient_reward_headroom_no_call", opportunity_gate)
        self.assertIn("lower_extreme_bear_continuation_pressure_insufficient_headroom", opportunity_gate)
        self.assertIn("points_from_session_low -lt 20.0", opportunity_gate)
        self.assertIn("support_reclaim_after_flush -lt 1.0", opportunity_gate)
        self.assertIn("points_above_prev_low -lt 0.0", opportunity_gate)

        management_guard = MANAGEMENT_GUARD.read_text(encoding="utf-8")
        self.assertIn("hermes-native-bounded.ps1", management_guard)
        self.assertIn("Invoke-HermesNativeBounded", management_guard)
        self.assertIn("management_prepare_timeout", management_guard)
        self.assertIn("Invoke-NativeCapture", management_guard)
        self.assertIn("ErrorActionPreference = 'Continue'", management_guard)
        self.assertIn("reason='no_open_protected_books'", management_guard)
        self.assertIn("portfolio_cycle_already_active", management_guard)
        self.assertIn("model_calls=0", management_guard)
        self.assertIn("ProfitTriggerUsd = 30.0", management_guard)
        self.assertIn("DeterministicProfitExit = $true", management_guard)
        self.assertIn("openBookDiagnostics", management_guard)
        self.assertIn("dollars_to_profit_trigger", management_guard)
        self.assertIn("dollars_to_adverse_trigger", management_guard)
        self.assertIn("open_book_diagnostics", management_guard)
        self.assertIn("deterministic_profit_exit_complete", management_guard)
        self.assertIn("model_calls=0", management_guard)
        self.assertIn("submit-validated-sim-exit.ps1", management_guard)
        self.assertIn("expected_actions = @('EXIT')", management_guard)
        self.assertIn("deterministic-profit-guard", management_guard)
        self.assertIn("AdverseTriggerUsd = -25.0", management_guard)
        self.assertIn("run-hermes-portfolio-cycle.ps1", management_guard)
        self.assertIn("-ManagementOnly", management_guard)
        self.assertIn("if ($SubmitSim) { $runnerArgs += '-SubmitSim' }", management_guard)
        self.assertIn("Compact Hermes prompt exceeds 24000 bytes", cycle)
        self.assertIn("prompt_over_limit", cycle)
        self.assertIn("MNQ underlying observation is stale", cycle)

        opportunity_guard = OPPORTUNITY_GUARD.read_text(encoding="utf-8")
        self.assertIn("-PrepareOnly", opportunity_guard)
        self.assertIn("hermes-opportunity-gate.ps1", opportunity_guard)
        self.assertIn("Get-HermesOpportunityGate", opportunity_guard)
        self.assertIn("portfolio_cycle_already_active", opportunity_guard)
        self.assertIn("Unified Hermes preparation did not include a market snapshot hash", opportunity_guard)
        self.assertIn("Snapshot hash changed before inference", opportunity_guard)
        self.assertIn("model_calls=0", opportunity_guard)
        self.assertIn("upper_breakout_acceptance_1m", opportunity_guard)
        self.assertIn("failed_upper_breakout_1m", opportunity_guard)
        self.assertIn("lower_breakdown_acceptance_1m", opportunity_guard)
        self.assertIn("failed_lower_breakdown_1m", opportunity_guard)
        self.assertIn("support_reclaim_after_flush", opportunity_guard)
        self.assertIn("upper_extreme_bear_turn_1m", opportunity_guard)
        self.assertIn("lower_extreme_bull_turn_1m", opportunity_guard)
        self.assertIn("lower_extreme_bear_continuation_pressure_1m", opportunity_guard)
        self.assertIn("lower_extreme_bear_continuation_pressure_5m", opportunity_guard)
        self.assertIn("lower_extreme_trend_pullback_short_1m", opportunity_guard)
        self.assertIn("filtered_soft_trigger", opportunity_guard)
        self.assertIn("points_to_prev_low_reclaim", opportunity_guard)
        self.assertIn("points_to_near_support_reclaim", opportunity_guard)
        self.assertIn("short_headroom_from_session_low", opportunity_guard)
        self.assertIn("points_to_short_headroom_30", opportunity_guard)
        self.assertIn("minimum_required_short_headroom", opportunity_guard)
        self.assertIn("points_to_short_headroom_required", opportunity_guard)
        self.assertIn("short_headroom_extension_buffer_points", opportunity_guard)
        self.assertIn("soft_trigger_credit_throttle", opportunity_guard)
        self.assertIn("soft_trigger_no_eligible_discovery_books", opportunity_guard)
        self.assertIn("softFallbackBooks", opportunity_guard)
        self.assertIn("support_reclaim_after_flush", opportunity_guard)
        self.assertIn("$softTriggers -contains 'upper_extreme_bear_turn_1m'", opportunity_guard)
        self.assertIn("$softTriggers -contains 'lower_extreme_trend_pullback_short_1m'", opportunity_guard)
        self.assertIn("$softTriggers -contains 'lower_extreme_bull_turn_1m'", opportunity_guard)
        self.assertIn("soft_fallback_books", opportunity_guard)
        self.assertIn("glitch-aggressive", opportunity_guard)
        self.assertIn("glitch-stay-revert", opportunity_guard)
        self.assertIn("glitch-conservative", opportunity_guard)
        self.assertIn("routeId -eq 'glitch'", opportunity_guard)
        self.assertIn("confirmedSoftTrigger", opportunity_guard)
        self.assertIn("conservativeSoftTrigger", opportunity_guard)
        self.assertNotIn("max_trades_per_day", opportunity_guard)
        self.assertNotIn("trade_cap_active", opportunity_guard)
        self.assertNotIn("cooldown_after_loss_active", opportunity_guard)
        self.assertIn("-not [bool]$_.daily_loss_lockout_active", opportunity_guard)
        self.assertIn("opportunity_runner_blocked", opportunity_guard)
        self.assertIn("runner_blocked", opportunity_guard)
        self.assertIn("blockedModelCalls = 0", opportunity_guard)
        self.assertIn("Compact Hermes prompt exceeds 24000 bytes", opportunity_guard)
        self.assertIn("exact_match", opportunity_guard)
        self.assertIn("run-hermes-portfolio-cycle.ps1", opportunity_guard)
        self.assertIn("runner-preparation.json", opportunity_guard)
        self.assertIn("-PreparationPath", opportunity_guard)
        self.assertIn("if ($SubmitSim) { $runnerArgs += '-SubmitSim' }", opportunity_guard)
        self.assertIn("daily_loss_lockout_active", opportunity_guard)
        self.assertIn("daily_loss_remaining_per_master_contract_usd", opportunity_guard)

        sim_guard_tick = SIM_GUARD_TICK.read_text(encoding="utf-8")
        self.assertIn("hermes-sim-guard-ticks.jsonl", sim_guard_tick)
        self.assertIn("Add-Content -LiteralPath $tickJournal", sim_guard_tick)

        sim_status = SIM_STATUS.read_text(encoding="utf-8")
        self.assertIn("glitch.hermes.sim_status.v1", sim_status)
        self.assertIn("route_caps", sim_status)
        self.assertNotIn("trade_cap_active", sim_status)
        self.assertNotIn("max_trades_per_day", sim_status)
        self.assertNotIn("cooldown_after_loss_active", sim_status)
        self.assertIn("group_entry_filled", sim_status)
        self.assertIn("last_guard_tick", sim_status)
        self.assertIn("recent_rejections", sim_status)
        self.assertIn("performance_summary", sim_status)
        self.assertIn("Get-LatestEntryConstraintSummary", sim_status)
        self.assertIn("current_entry_constraints", sim_status)
        self.assertIn("Get-GuardHealthSummary", sim_status)
        self.assertIn("guard_health", sim_status)
        self.assertIn("runner_blocked_count", sim_status)
        self.assertIn("recovered_after_last_blocker", sim_status)
        self.assertIn("last_actionable_trigger", sim_status)
        self.assertIn("risk_books", sim_status)
        self.assertIn("waiting_for", sim_status)
        self.assertIn("min_risk_per_master_contract_usd", sim_status)
        self.assertIn("volatility_stop_floor_usd", sim_status)
        self.assertIn("noise_floor_stop_points", sim_status)
        self.assertIn("short_reward_headroom_plus_", sim_status)
        self.assertIn("points_to_short_headroom_required", sim_status)
        self.assertIn("short_headroom_extension_buffer_points", sim_status)
        self.assertIn("Summarize-Outcomes", sim_status)
        self.assertIn("avg_account_giveback_usd", sim_status)
        self.assertIn("stopped_after_mfe_35_count", sim_status)
        self.assertIn("profitCaptureTriggerUsd = 30.0", sim_status)
        self.assertIn("profit_capture_trigger_usd", sim_status)
        self.assertIn("profit_capture_eligible_legs", sim_status)
        self.assertIn("hypothetical_group_pnl_at_30_capture_usd", sim_status)
        self.assertIn("hypothetical_improvement_at_30_capture_usd", sim_status)
        self.assertIn("Bankable MFE was surrendered", sim_status)
        self.assertIn("executor_enabled", sim_status)
        self.assertIn("eligible_for_management", sim_guard_tick)
        self.assertIn("hermes-native-bounded.ps1", sim_guard_tick)
        self.assertIn("Invoke-HermesNativeBounded", sim_guard_tick)
        self.assertIn("management_prepare_timeout", sim_guard_tick)
        self.assertIn("run-hermes-management-guard.ps1", sim_guard_tick)
        self.assertIn("run-hermes-opportunity-guard.ps1", sim_guard_tick)
        self.assertIn("management_guard_tick_complete", sim_guard_tick)
        self.assertIn("ManagementPolls = 6", sim_guard_tick)
        self.assertIn("ManagementPollIntervalSeconds = 10", sim_guard_tick)
        self.assertIn("AdverseTriggerUsd','-999999", sim_guard_tick)
        self.assertIn("management_guard_poll_complete", sim_guard_tick)
        self.assertIn("opportunity_guard_tick_complete", sim_guard_tick)
        self.assertIn("sim_trade_opened", sim_guard_tick)
        self.assertIn("post_entry_management_guard_tick_complete", sim_guard_tick)
        self.assertIn("A fresh MNQ entry can reach bankable MFE before the next scheduled tick", sim_guard_tick)
        self.assertIn("Post-entry management poll failed", sim_guard_tick)
        self.assertIn("if ([string]$guard.event -eq 'deterministic_profit_exit_complete') { return }", sim_guard_tick)
        self.assertIn("if ([string]$guard.reason -eq 'no_open_protected_books') { return }", sim_guard_tick)
        self.assertIn("if ($SubmitSim) { $args += '-SubmitSim' }", sim_guard_tick)
        self.assertIn("if ($SubmitSim) { $opportunityArgs += '-SubmitSim' }", sim_guard_tick)

        scheduler = SIM_GUARD_SCHEDULER.read_text(encoding="utf-8")
        self.assertIn("run-hermes-sim-guard-tick.ps1", scheduler)
        self.assertIn("[switch]$WhatIfOnly", scheduler)
        self.assertIn("MultipleInstances IgnoreNew", scheduler)
        self.assertIn("RepetitionInterval", scheduler)
        self.assertNotIn("New-ScheduledTaskRepetitionSettings", scheduler)
        self.assertIn("RunLevel Limited", scheduler)
        self.assertNotIn("RunLevel Highest", scheduler)
        self.assertIn("Register-ScheduledTask", scheduler)
        self.assertIn("registered = $false", scheduler)
        self.assertIn("registered = $true", scheduler)

        reconciler = (ROOT / "tools/hermes/reconcile-hermes-outcomes.py").read_text(encoding="utf-8")
        self.assertIn("incomplete_outcome = False", reconciler)
        self.assertIn('read_trade_ledger(glitch_data / "TradeLedger.tsv")', reconciler)
        self.assertIn("_match_ledger_trades", reconciler)
        self.assertIn("master_entry_submitted", reconciler)
        self.assertIn("follower_structural_brackets_submitted", reconciler)
        self.assertIn("terminal_group_snapshot", reconciler)
        self.assertIn('int(row.get("working_orders") or 0) != 0', reconciler)
        self.assertIn("len(account_outcomes) != len(expected_accounts)", reconciler)
        self.assertIn("MNQ ${minutes}m observation is stale", cycle)
        self.assertIn("Test-CompiledKnownMicroContractFallback", cycle)
        self.assertIn("expected_fallback_contract", cycle)
        self.assertIn("compiled_contract_fallback_available", cycle)
        self.assertIn("NinjaTrader.Custom.dll", cycle)
        self.assertIn("GlitchInstrumentMetadataService.cs", cycle)
        self.assertIn("instrument_contract_gate_active", cycle)
        self.assertIn("daily_loss_lockout_active", cycle)
        self.assertIn("daily_loss_remaining_per_master_contract_usd", cycle)
        self.assertIn("max_daily_loss_usd", cycle)
        self.assertIn("-not $dailyLossLockoutActive", cycle)
        self.assertIn("expected_fallback_contract", opportunity_guard)
        self.assertIn("compiled_contract_fallback_available", opportunity_guard)
        self.assertIn("mnq_market_contract", sim_status)
        self.assertIn("expected_fallback_contract", sim_status)
        self.assertIn("compiled_contract_fallback_available", sim_status)

    def test_managed_exit_is_exact_sim_only_one_shot_and_unarmed(self):
        text = SIM_EXIT_SUBMIT.read_text(encoding="utf-8")
        self.assertIn("Sim exit submitter accepts only EXIT", text)
        self.assertIn("Managed exit refused non-Sim group member", text)
        self.assertIn("requires exactly one MNQ position", text)
        self.assertIn("requires complete stop/target bracket pairs", text)
        self.assertIn("($workingOrders % 2) -ne 0", text)
        self.assertIn("sim-submit.lock", text)
        self.assertIn("$policyBefore.mode = 'sim'", text)
        self.assertIn("$policyBefore.executor_enabled = $true", text)
        self.assertIn("$originalPolicyJson", text)
        self.assertIn("group_exit_submitted", text)
        self.assertIn("group_flat_no_working_orders", text)
        self.assertIn("executor_left_armed = $false", text)

    def test_data_capsule_uses_active_archetype_v2_only(self):
        text = BUILD_CAPSULE.read_text(encoding="utf-8")
        self.assertIn("glitch_hermes_docs\\memory\\archetypes.v2.json", text)
        self.assertIn("knowledge\\archetypes.v2.json", text)
        self.assertIn("knowledge\\archetypes.v1.json", text)
        self.assertIn("Remove-Item -LiteralPath", text)

    def test_trade_history_is_attributable_but_not_an_entry_gate(self):
        history = HISTORY.read_text(encoding="utf-8")
        firewall = FIREWALL.read_text(encoding="utf-8")
        executor = EXECUTOR.read_text(encoding="utf-8")
        self.assertIn('MessageHasToken(message, "master", account)', history)
        self.assertNotIn("CountTradesTodayUtc(account, nowUtc)", firewall)
        self.assertNotIn("GetLastEnterUtc(account, instrument, nowUtc)", firewall)
        self.assertIn('"|master="', executor)

    def test_trade_limits_count_filled_group_entries_not_accepted_intents(self):
        history = HISTORY.read_text(encoding="utf-8")
        executor = EXECUTOR.read_text(encoding="utf-8")
        self.assertIn('FilledExecutionCode = "group_entry_filled"', history)
        self.assertIn("GetExecutionsJsonlPath", history)
        self.assertIn("HashSet<string>", history)
        self.assertNotIn("GetDecisionsJsonlPath", history)
        self.assertNotIn("GetReceivedJsonlPath", history)
        self.assertIn('"group_entry_filled"', executor)
        self.assertIn('"group_entry_open_protected"', executor)
        self.assertIn("entry.Filled == entry.Quantity", executor)
        self.assertIn("HasExactOwnedExposure(group, accountIndex)", executor)
        self.assertIn("IsWorkingOrderState(stop.OrderState)", executor)
        self.assertIn("IsWorkingOrderState(target.OrderState)", executor)

    def test_first_trade_loop_is_single_position_and_terminal(self):
        text = FIRST_TRADE_LOOP.read_text(encoding="utf-8")
        self.assertIn("first-paper-trade-cycle.lock", text)
        self.assertIn("Sim group is not flat/order-free", text)
        self.assertIn("if ($cycleRecord.action -eq 'NOTHING') { return }", text)
        self.assertIn("submit-validated-sim-intent.ps1", text)
        self.assertIn("executor_left_armed = $false", text)
        self.assertIn("first_paper_trade_closed", text)
        self.assertIn("$state.status = 'closed'", text)

    def test_live_cycle_redacts_private_runtime_state_from_model_capsule(self):
        text = CYCLE.read_text(encoding="utf-8")
        self.assertIn("$modelCycle", text)
        self.assertIn("$validationCycle", text)
        self.assertIn("$validationCycle | ConvertTo-Json", text)
        self.assertIn("[switch]$PrepareOnly", text)
        self.assertIn("transmitted = $false", text)
        self.assertIn("No portfolio, balances, PnL, positions, orders, allowlists, or private policy", text)
        self.assertIn("Local Sim group is not flat; no external inference.", text)
        self.assertIn("Local Sim group has working orders or incomplete order state; no external inference.", text)
        self.assertIn("local_safety_attestation", text)
        self.assertIn("risk_per_contract_usd_range = @($explorationRiskMinimum,$explorationRiskMaximum)", text)
        self.assertIn("$localRiskCeiling", text)
        self.assertIn("$groupContractMultiplier", text)
        self.assertIn("risk_budget_source = 'local_aggregate_safety_limit'", text)
        self.assertIn("preferred_minimum_reward_risk = 1.5", text)
        self.assertIn("MNQ decision price is unavailable; no external inference.", text)
        self.assertIn("Market envelope is stale or future-dated; no external inference.", text)
        model_block = text.split("$modelCycle = [ordered]@{", 1)[1].split("$activeDir =", 1)[0]
        self.assertNotIn("portfolio =", model_block)
        self.assertNotIn("policy =", model_block)

    def test_trading_epoch_reset_is_preview_first_and_preserves_chat(self):
        reset = TRADING_EPOCH_RESET.read_text(encoding="utf-8")
        helper = NAMED_SESSION_RESET.read_text(encoding="utf-8")
        self.assertIn("[switch]$Apply", reset)
        self.assertIn("if (-not $Apply)", reset)
        self.assertIn("All Glitch Hermes cron jobs must be paused before reset", reset)
        self.assertIn("named-trading-session.jsonl", reset)
        self.assertIn("'memories\\USER.md'", reset)
        self.assertIn("'journal\\nt'", reset)
        self.assertIn("'Journal.tsv', 'TradeLedger.tsv'", reset)
        self.assertIn('args.title != "trading"', helper)
        self.assertIn('args.preserve_title != "chat"', helper)
        self.assertIn("db.delete_session(old_id)", helper)
        self.assertIn("db.resolve_session_by_title(args.preserve_title) != preserved_id", helper)


if __name__ == "__main__":
    unittest.main()
