param(
    [string]$JsonPath = "D:\ab\projects\glitch\Glitch-Platform\ninjatrader\Glitch\AddOns\GlitchAddOn\Resources\PropFirmRules.json",
    [string]$OutputPath = "D:\ab\projects\glitch\Glitch-Platform\ninjatrader\Glitch\AddOns\GlitchAddOn\UI\MainWindow\GlitchMainWindow.PropFirmRulesBundle.generated.cs"
)

$ErrorActionPreference = "Stop"

if (-not (Test-Path -LiteralPath $JsonPath)) {
    throw "Prop firm rules JSON not found: $JsonPath"
}

$json = [System.IO.File]::ReadAllText($JsonPath, [System.Text.Encoding]::UTF8)
$base64 = [Convert]::ToBase64String([System.Text.Encoding]::UTF8.GetBytes($json))

$chunks = for ($i = 0; $i -lt $base64.Length; $i += 120) {
    $length = [Math]::Min(120, $base64.Length - $i)
    $base64.Substring($i, $length)
}

$base64Lines = if ($chunks.Count -eq 1) {
    "            `"$($chunks[0])`";"
} else {
    ($chunks | ForEach-Object { "                `"$($_)`"" }) -join " +`r`n"
}

$content = @"
//
// Generated from Resources/PropFirmRules.json by scripts/generate_bundled_prop_rules.ps1.
// Do not edit this file manually.
//

using System;

namespace Glitch.UI
{
    public partial class GlitchMainWindow
    {
        private static string TryReadBundledPropFirmRulesJson()
        {
            try
            {
                const string base64 =
$base64Lines
                ;

                if (string.IsNullOrWhiteSpace(base64))
                    return null;

                byte[] bytes = Convert.FromBase64String(base64);
                return System.Text.Encoding.UTF8.GetString(bytes);
            }
            catch
            {
                return null;
            }
        }
    }
}
"@

$outputDirectory = Split-Path -Parent $OutputPath
if (-not [string]::IsNullOrWhiteSpace($outputDirectory)) {
    [System.IO.Directory]::CreateDirectory($outputDirectory) | Out-Null
}

$utf8NoBom = New-Object System.Text.UTF8Encoding($false)
[System.IO.File]::WriteAllText($OutputPath, $content, $utf8NoBom)
